### ISSUE TITLE
apparent error getting isFile for a .gitignore file

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#10]
modifiedAt:Wed Dec 18 12:41:39 EST 2013
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.io.IRODSFileImpl  - isFile() for path:/fedZone1/home/test1/demo/irodsidrop/.gitignore
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.io.IRODSFileInputStream  - openIRODSFile()
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - isFileExists()
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - checking existence of: /fedZone1/home/test1/demo/irodsidrop/.gitignore
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.io.IRODSFileInputStream  - opening the file
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.io.IRODSFileImpl  - opening irodsFile:/fedZone1/home/test1/demo/irodsidrop/.gitignore
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - isFileExists()
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - checking existence of: /fedZone1/home/test1/demo/irodsidrop/.gitignore
59836 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - openFile(final IRODSFile irodsFile,final DataObjInp.OpenFlags openFlags)
59839 [http-bio-8081-exec-5] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - opening file:/fedZone1/home/test1/demo/irodsidrop/.gitignore
59851 [http-bio-8081-exec-5] ERROR org.irods.jargon.core.pub.io.IRODSFileInputStream  - JargonException caught in constructor, rethrow as JargonRuntimeException
org.irods.jargon.core.exception.JargonException: Unknown iRODS exception code recieved:-510002
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:103)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1136)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:589)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:555)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:209)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:113)
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.openFile(IRODSFileSystemAOImpl.java:909)
	at org.irods.jargon.core.pub.io.IRODSFileImpl.openWithMode(IRODSFileImpl.java:1289)
	at org.irods.jargon.core.pub.io.IRODSFileImpl.openReadOnly(IRODSFileImpl.java:1306)
	at org.irods.jargon.core.pub.io.IRODSFileInputStream.openIRODSFile(IRODSFileInputStream.java:172)
	at org.irods.jargon.core.pub.io.IRODSFileInputStream.openFile(IRODSFileInputStream.java:109)
	at org.irods.jargon.core.pub.io.IRODSFileInputStream.<init>(IRODSFileInputStream.java:93)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImpl.instanceIRODSFileInputStream(IRODSFileFactoryImpl.java:563)
	at org.irods.jargon.core.pub.DataObjectAOImpl.computeSHA1ChecksumOfIrodsFileByReadingDataFromStream(DataObjectAOImpl.java:4059)
	at org.irods.jargon.modeshape.connector.IRODSWriteableConnector.sha1(IRODSWriteableConnector.java:413)
	at org.irods.jargon.modeshape.connector.IRODSWriteableConnector.createBinaryValue(IRODSWriteableConnector.java:387)
	at org.irods.jargon.modeshape.connector.IRODSWriteableConnector.binaryFor(IRODSWriteableConnector.java:359)
	at org.irods.jargon.modeshape.connector.IRODSWriteableConnector.getDocumentById(IRODSWriteableConnector.java:550)
	at org.modeshape.jcr.federation.FederatedDocumentStore.get(FederatedDocumentStore.java:263)
	at org.modeshape.jcr.cache.document.WorkspaceCache.documentFor(WorkspaceCache.java:164)
	at org.modeshape.jcr.cache.document.WorkspaceCache.documentFor(WorkspaceCache.java:183)
	at org.modeshape.jcr.cache.document.WorkspaceCache.getNode(WorkspaceCache.java:215)
	at org.modeshape.jcr.cache.document.AbstractSessionCache.getNode(AbstractSessionCache.java:237)
	at org.modeshape.jcr.cache.document.WritableSessionCache.getNode(WritableSessionCache.java:169)
	at org.modeshape.jcr.cache.document.AbstractSessionCache.getNode(AbstractSessionCache.java:242)
	at org.modeshape.jcr.JcrSession.cachedNode(JcrSession.java:597)
	at org.modeshape.jcr.JcrSession.node(JcrSession.java:626)
	at org.modeshape.jcr.JcrSession.node(JcrSession.java:645)
	at org.modeshape.jcr.JcrSession.getItem(JcrSession.java:864)
	at org.modeshape.jcr.JcrSession.findItem(JcrSession.java:667)
	at org.modeshape.jcr.JcrSession.findItem(JcrSession.java:650)
	at org.modeshape.jcr.AbstractJcrNode.getProperty(AbstractJcrNode.java:319)
	at org.modeshape.jcr.AbstractJcrNode.getProperty(AbstractJcrNode.java:108)
	at org.modeshape.web.jcr.webdav.DefaultContentMapper.getLastModified(DefaultContentMapper.java:116)
	at org.modeshape.web.jcr.webdav.ModeShapeWebdavStore.getStoredObject(ModeShapeWebdavStore.java:363)
	at org.modeshape.webdav.methods.DoPropfind.parseProperties(DoPropfind.java:254)
	at org.modeshape.webdav.methods.DoPropfind.recursiveParseProperties(DoPropfind.java:208)
	at org.modeshape.webdav.methods.DoPropfind.recursiveParseProperties(DoPropfind.java:222)
	at org.modeshape.webdav.methods.DoPropfind.execute(DoPropfind.java:157)
	at org.modeshape.webdav.WebDavServletBean.service(WebDavServletBean.java:141)
	at org.modeshape.web.jcr.webdav.ModeShapeWebdavServlet.service(ModeShapeWebdavServlet.java:130)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)

**Comment by michael-conway** [comment]
added unit test, passes

```Java

/**
	 * Bug https://github.com/DICE-UNC/jargon/issues/10 apparent error getting
	 * isFile for a .gitignore file #10
	 */
	@Test
	public final void testExistsDotGitignoreBug10() throws Exception {
		String testFileName = ".gitignore";
		String absPath = scratchFileUtils
				.createAndReturnAbsoluteScratchPath(IRODS_TEST_SUBDIR_PATH);
		FileGenerator.generateFileOfFixedLengthGivenName(absPath, testFileName,
				8);

		String targetIrodsCollection = testingPropertiesHelper
				.buildIRODSCollectionAbsolutePathFromTestProperties(
						testingProperties, IRODS_TEST_SUBDIR_PATH);

		StringBuilder fileNameAndPath = new StringBuilder();
		fileNameAndPath.append(absPath);

		fileNameAndPath.append(testFileName);

		IRODSAccount irodsAccount = testingPropertiesHelper
				.buildIRODSAccountFromTestProperties(testingProperties);
		IRODSAccessObjectFactory accessObjectFactory = irodsFileSystem
				.getIRODSAccessObjectFactory();
		DataTransferOperations dto = accessObjectFactory
				.getDataTransferOperations(irodsAccount);
		dto.putOperation(fileNameAndPath.toString(), targetIrodsCollection, "",
				null, null);

		IRODSFileFactory irodsFileFactory = accessObjectFactory
				.getIRODSFileFactory(irodsAccount);
		IRODSFile irodsFile = irodsFileFactory
				.instanceIRODSFile(targetIrodsCollection + '/' + testFileName);

		Assert.assertTrue(irodsFile.exists());
	}


111
