### ISSUE TITLE
Read length set to zero on replication with iRODS 4.1

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#106]
DataObjectImplTest testReplicate fails at replication step

Unit Test

```Java

@Test
	public final void testReplicate() throws Exception {
		// generate a local scratch file

		String testFileName = "testReplicate1.txt";
		String absPath = scratchFileUtils
				.createAndReturnAbsoluteScratchPath(IRODS_TEST_SUBDIR_PATH);
		String fileNameOrig = FileGenerator.generateFileOfFixedLengthGivenName(
				absPath, testFileName, 2);

		String targetIrodsCollection = testingPropertiesHelper
				.buildIRODSCollectionAbsolutePathFromTestProperties(
						testingProperties, IRODS_TEST_SUBDIR_PATH);

		IRODSAccount irodsAccount = testingPropertiesHelper
				.buildIRODSAccountFromTestProperties(testingProperties);

		IRODSFile irodsFile = irodsFileSystem.getIRODSFileFactory(irodsAccount)
				.instanceIRODSFile(targetIrodsCollection + "/" + testFileName);
		irodsFile.deleteWithForceOption();

		irodsFile.setResource(testingProperties
				.getProperty(TestingPropertiesHelper.IRODS_RESOURCE_KEY));
		File localFile = new File(fileNameOrig);

		DataObjectAOImpl dataObjectAO = (DataObjectAOImpl) irodsFileSystem
				.getIRODSAccessObjectFactory().getDataObjectAO(irodsAccount);

		dataObjectAO.putLocalDataObjectToIRODS(localFile, irodsFile, true);

		dataObjectAO
				.replicateIrodsDataObject(
						targetIrodsCollection + '/' + testFileName,
						testingProperties
								.getProperty(TestingPropertiesHelper.IRODS_SECONDARY_RESOURCE_KEY));

		List<Resource> resources = dataObjectAO
				.listFileResources(targetIrodsCollection + "/" + testFileName);
		Assert.assertEquals("did not find expected resources", 2,
				resources.size());

	}



```
Jargon log

```

60016 [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - calling irods function with byte array
60016 [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - calling irods function with:<DataObjInp_PI><objPath>/tempZone/home/test1/jargon-scratch/dataObjectAOImplTest/testReplicate1.txt</objPath>
<createMode>0</createMode>
<openFlags>0</openFlags>
<offset>0</offset>
<dataSize>0</dataSize>
<numThreads>0</numThreads>
<oprType>6</oprType>
<KeyValPair_PI><ssLen>1</ssLen>
<keyWord>destRescName</keyWord>
<svalue>test1-resc2</svalue>
</KeyValPair_PI>
</DataObjInp_PI>

60016 [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - api number is:610
60016 [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - functionID: 610
60016 [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - header:<MsgHeader_PI><type>RODS_API_REQ</type><msgLen>379</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>610</intInfo></MsgHeader_PI>
60016 [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - reading message from irods
60016 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  4
60016 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
60016 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 4
60172 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  0
60173 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
60173 [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 0
60173 [main] ERROR org.irods.jargon.core.connection.AbstractConnection  - read length is set to zero
60174 [main] ERROR org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - io exception
java.io.IOException: read length is set to zero
	at org.irods.jargon.core.connection.AbstractConnection.read(AbstractConnection.java:554)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readHeader(AbstractIRODSMidLevelProtocol.java:1011)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:646)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:231)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:571)
	at org.irods.jargon.core.pub.DataObjectAOImpl.replicateIrodsDataObject(DataObjectAOImpl.java:2478)
	at org.irods.jargon.core.pub.DataObjectAOImplTest.testReplicate(DataObjectAOImplTest.java:2621)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```
iRODS Log

```





irodsAgent: /home/test/workspace-irods/irods/external/boost_1_58_0/boost/smart_ptr/shared_ptr.hpp:648: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = irods::api_entry; typename boost::detail::sp_member_access<T>::type = irods::api_entry*]: Assertion `px != 0' failed.
packed XML: 
<MsgHeader_PI>
<type>RODS_API_REPLY</type>
<msgLen>0</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>

sending header: len = 139
<MsgHeader_PI>
<type>RODS_API_REPLY</type>
<msgLen>0</msgLen>
<errorLen>0</errorLen>
<bsLen>0</bsLen>
<intInfo>0</intInfo>
</MsgHeader_PI>

received header: len = 134
<MsgHeader_PI><type>RODS_API_REQ</type><msgLen>379</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>610</intInfo></MsgHeader_PI>
received msg: 
<DataObjInp_PI><objPath>/tempZone/home/test1/jargon-scratch/dataObjectAOImplTest/testReplicate1.txt</objPath>
<createMode>0</createMode>
<openFlags>0</openFlags>
<offset>0</offset>
<dataSize>0</dataSize>
<numThreads>0</numThreads>
<oprType>6</oprType>
<KeyValPair_PI><ssLen>1</ssLen>
<keyWord>destRescName</keyWord>
<svalue>test1-resc2</svalue>
</KeyValPair_PI>
</DataObjInp_PI>

May  7 11:29:29 pid:7445 NOTICE: Agent process 21403 exited with status 134





```

**Comment by michael-conway** [comment]
note ilsresc shows (due to a misconfiguration in the unit tests elsewhere:

```Shell

irods@irodsLinux:~/iRODS$ ilsresc
demoResc
test1-resc
test1-resc3
testAddChildToParent:deferred
└── test1-resc2



```


One would expect a direct access exception rather than an agent crash

**Comment by michael-conway** [comment]
apparently a protocol change in 4.1?

```

test@irodsLinux:~$ irepl -R test1-resc2 testReplicate1.txt
test@irodsLinux:~$ ils -LA
/tempZone/home/test1/jargon-scratch/dataObjectAOImplTest:
        ACL - test1#tempZone:own   
        Inheritance - Disabled
  test1             0 test1-resc            2 2015-05-07.11:46 & testReplicate1.txt
        generic    /var/lib/irods/iRODS/Vault1/home/test1/jargon-scratch/dataObjectAOImplTest/testReplicate1.txt
        ACL - test1#tempZone:own   
  test1             1 test1-resc2            2 2015-05-07.11:48 & testReplicate1.txt
        generic    /var/lib/irods/iRODS/Vault2/home/test1/jargon-scratch/dataObjectAOImplTest/testReplicate1.txt
        ACL - test1#tempZone:own   
test@irodsLinux:~$ 



```

**Comment by michael-conway** [comment]
data obj API # has changed from 610 -> 695
