### ISSUE TITLE
localized test failure setting password for user as admin

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#130]
Error running DataObjectAOImplTest on my computer at home, does not surface anywhere else.  This needs to be looked at

No failures in CI.

```
org.irods.jargon.core.exception.JargonException: Unknown iRODS exception code recieved:-850000
    at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:110)
    at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
    at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
    at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
    at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:231)
    at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
    at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:571)
    at org.irods.jargon.core.pub.UserAOImpl.changeAUserPasswordByAnAdmin(UserAOImpl.java:806)
    at org.irods.jargon.core.pub.DataObjectAOImplTest.testSetPermissionsForUserInGroupToObject(DataObjectAOImplTest.java:4041)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

When running

``` Java


/**
     * bug [#1575] [iROD-Chat:10314] jargon-core permissions issue
     *
     * @throws Exception
     */
    @Ignore
    public final void testSetPermissionsForUserInGroupToObject()
            throws Exception {
        // generate a local scratch file

        String testFileName = "testSetPermissionsForUserInGroupToObject.txt";
        String absPath = scratchFileUtils
                .createAndReturnAbsoluteScratchPath(IRODS_TEST_SUBDIR_PATH);
        String fileNameOrig = FileGenerator.generateFileOfFixedLengthGivenName(
                absPath, testFileName, 2);

        String testUser = "testUserInGroup123";
        String testGroup = "testGroupForTestingUser123";
        String newPassword = "blargh";

        String targetIrodsCollection = testingPropertiesHelper
                .buildIRODSCollectionAbsolutePathFromTestProperties(
                        testingProperties, IRODS_TEST_SUBDIR_PATH);

        IRODSAccount irodsAccount = testingPropertiesHelper
                .buildIRODSAccountFromTestProperties(testingProperties);

        UserAO userAO = irodsFileSystem.getIRODSAccessObjectFactory()
                .getUserAO(irodsAccount);
        UserGroupAO userGroupAO = irodsFileSystem.getIRODSAccessObjectFactory()
                .getUserGroupAO(irodsAccount);

        try {
            userAO.deleteUser(testUser);
            userGroupAO.removeUserGroup(testGroup);
        } catch (Exception e) {
            // ignore
        }

        User user = new User();
        user.setUserType(UserTypeEnum.RODS_USER);
        user.setName(testUser);
        userAO.addUser(user);
        userAO.changeAUserPasswordByAnAdmin(testUser, newPassword);

        UserGroup userGroup = new UserGroup();
        userGroup.setUserGroupName(testGroup);
        userGroup.setZone(irodsAccount.getZone());
        userGroupAO.addUserGroup(userGroup);
        userGroupAO.addUserToGroup(testGroup, testUser, irodsAccount.getZone());

        DataObjectAOImpl dataObjectAO = (DataObjectAOImpl) irodsFileSystem
                .getIRODSAccessObjectFactory().getDataObjectAO(irodsAccount);
        IRODSFile irodsFile = irodsFileSystem.getIRODSFileFactory(irodsAccount)
                .instanceIRODSFile(targetIrodsCollection);
        dataObjectAO.putLocalDataObjectToIRODS(new File(fileNameOrig),
                irodsFile, true);

        dataObjectAO.setAccessPermissionRead("", targetIrodsCollection + "/"
                + testFileName, testGroup);

        // log in as the group user and test read access
        IRODSAccount secondaryAccount = testingPropertiesHelper
                .buildIRODSAccountForIRODSUserFromTestPropertiesForGivenUser(
                        testingProperties, testUser, newPassword);
        IRODSFile irodsFileForSecondaryUser = irodsFileSystem
                .getIRODSFileFactory(secondaryAccount).instanceIRODSFile(
                        targetIrodsCollection + "/" + testFileName);

        FilePermissionEnum filePermissionEnum = dataObjectAO
                .getPermissionForDataObject(
                        irodsFileForSecondaryUser.getAbsolutePath(),
                        secondaryAccount.getUserName(), "");

        Assert.assertEquals("should have found read permissions",
                FilePermissionEnum.READ, filePermissionEnum);

    }




```

**Comment by michael-conway** [comment]
restored test, successful
