### ISSUE TITLE
failing parallel file operation should throw exception

### ISSUE THREAD

**Issue by carsten-jahn** [DICE-UNC/jargon#133]
In a related ticket (#132), we noticed log messages like those:

```
2181 [pool-1-thread-7] ERROR org.irods.jargon.core.transfer.ParallelPutTransferThread  - error writing to iRODS parallel transfer socket
java.net.SocketException: Software caused connection abort: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.readWriteLoopForCurrentHeaderDirective(ParallelPutTransferThread.java:341)
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.put(ParallelPutTransferThread.java:290)
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.call(ParallelPutTransferThread.java:169)
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.call(ParallelPutTransferThread.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
2185 [pool-1-thread-7] ERROR org.irods.jargon.core.transfer.ParallelPutTransferThread  - An IO exception occurred during a parallel file put operation
org.irods.jargon.core.exception.JargonException: java.net.SocketException: Software caused connection abort: socket write error
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.readWriteLoopForCurrentHeaderDirective(ParallelPutTransferThread.java:417)
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.put(ParallelPutTransferThread.java:290)
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.call(ParallelPutTransferThread.java:169)
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.call(ParallelPutTransferThread.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Software caused connection abort: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
    at org.irods.jargon.core.transfer.ParallelPutTransferThread.readWriteLoopForCurrentHeaderDirective(ParallelPutTransferThread.java:341)
    ... 7 more
```

However, Jargon does not propagate errors up from the multithreaded parallel file transfer code to the main DataTransferOperations.putOperation method. Although we see these errors in the log file, our call of the putOperation returns as if it was successful.

I think it is important to fail with exceptions whenever a change was not persisted to iRODS (same is true for the icommands of course). Please extend exception handling to cover multithreaded cases in Jargon.

**Comment by michael-conway** [comment]
I'll bump this over into the 4.2 testing while folks may chime in on ths 'fail fast' idea.  At the risk of cliche, this behavior is a feature, not a bug, but happy to add a switch in the configuration to immediately fail.
