### ISSUE TITLE
TLS v1 being used in SSL pam auth

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#154]
Re Re: [iROD-Chat:14499] iDrop PAM Authentication Error

```


Sorry about repeating the topic, I saw the replies about wrong certificate and trust store, but it seems there is one more problem which I can't figure out from the logs...

Here is my story. I run irods 1.4.3. I installed tomcat7 and jdk7 and idrop-web2 in the icat server. Everything works fine with standard irods authentication mechanism.. but when I started to test it with PAM I got java.net.SocketException: Connection reset.

With ssl debug turned on (-Djavax.net.debug=all) I've noticed that TLSv1 is used:

http-bio-8080-exec-1, handling exception: java.net.SocketException: Connection reset
http-bio-8080-exec-1, SEND TLSv1 ALERT:  fatal, description = unexpected_message
http-bio-8080-exec-1, WRITE: TLSv1 Alert, length = 2
http-bio-8080-exec-1, Exception sending alert: java.net.SocketException: Broken pipe
http-bio-8080-exec-1, called closeSocket()
2015-11-02 11:00:43,453 [http-bio-8080-exec-1] ERROR connection.AuthMechanism  - ssl exception in handshake
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at org.irods.jargon.core.connection.PAMAuth.processAuthenticationAfterSt



```

**Comment by michael-conway** [comment]
link this to issue #155 

I am currently seeing SSL errors running JDK1.7 against the latest iRODS versions.  These have been SSL handshake/unknown protocol errors with the 4.1.7 codebase (iRODS master).  Switching to JDK 1.8 brings in SSL versions and algos that seem to work.

**Comment by trel** [comment]
please note that the iRODS `4-1-stable` branch is headed to `4.1.7`

and the `master` branch will become `4.2.0`
