### ISSUE TITLE
-2101000 iRODS exception code with PAM authentication

### ISSUE THREAD

**Issue by dkocher** [DICE-UNC/jargon#157]
When attempting to authenticate with PAM, the following error is returned. Note that `checkServerTrusted` of the custom trust manager set is never invoked.

```
Caused by: org.irods.jargon.core.exception.JargonException: Unknown iRODS exception code recieved:-2101000
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:110)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:231)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:571)
	at org.irods.jargon.core.connection.PAMAuth.processAuthenticationAfterStartup(PAMAuth.java:50)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:81)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:255)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:103)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:146)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:69)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:507)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:396)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:80)
```

**Comment by dkocher** [comment]
Some more logging output

```
425 [main] INFO org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl  - authenticateIRODSAccount()
425 [main] WARN org.irods.jargon.core.connection.IRODSSession  - closing session that is already closed, silently ignore
436 [main] INFO org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - instance() method...calling connection life cycle
436 [main] INFO org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - create connection....
436 [main] INFO org.irods.jargon.core.connection.IRODSTCPConnectionFactoryImpl  - instance()
439 [main] INFO org.irods.jargon.core.connection.AbstractConnection  - AbstractConnection()
440 [main] INFO org.irods.jargon.core.connection.AbstractConnection  - opening irods socket
645 [main] INFO org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - ...have connection, now authenticate given the auth scheme in the iRODS account...
645 [main] INFO org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - authenticate()
645 [main] INFO org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - get auth mechanism
646 [main] INFO org.irods.jargon.core.connection.AuthenticationFactoryImpl  - instanceAuthMechanism()
647 [main] INFO org.irods.jargon.core.connection.AuthenticationFactoryImpl  - authScheme:PAM
648 [main] INFO org.irods.jargon.core.connection.AuthenticationFactoryImpl  - using PAM auth
650 [main] INFO org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - authenticate...
1105 [main] INFO org.irods.jargon.core.connection.AuthMechanism  - startup response:StartupResponseData:
   status:0
   relVersion:rods3.3.1
   apiVersion:d
   reconnPort:20185
   reconnAddr:data.iplantcollaborative.org
   cookie:846930886
1106 [main] INFO org.irods.jargon.core.connection.AuthMechanism  - startSSL for PAM auth

```

**Comment by michael-conway** [comment]
OK did you set the trust manager in IRODS Session?

/**
      * @param x509TrustManager
      *            the x509TrustManager to set, this may be left
      *            <code>null</code>, in which case a default trust 
manager is
      *            used. this allows users to inject their own 
certificate trust
      *            manager. Note as well that {@link JargonProperties} 
can also
      *            specifiy that a 'trust all' trust manager should be 
used, in
      *            which case the {@link TrustAllX509TrustManager} will be
      *            created and put here. This creation is only done when
      *            constructing iRODS session using the constructor that 
takes a
      *            <code>JargonProperties</code> parameter, with the 
bypassSslCet
      */
     public synchronized void setX509TrustManager(
             final X509TrustManager x509TrustManager) {
         this.x509TrustManager = x509TrustManager;
     }





This should be used in the PAM auth like so..

// start ssl
         log.info("startSSL for PAM auth");
         SSLStartInp sslStartInp = SSLStartInp.instance();
         irodsCommands.irodsFunction(sslStartInp);

         SSLContext ctx;
         try {
             ctx = SSLContext.getInstance("TLS", "SunJSSE");
         } catch (NoSuchAlgorithmException | NoSuchProviderException e) {
             // The SunJSSE provider should always be available.
             throw new AssertionError(e);
         }

         TrustManager[] trustManagers = null;

         if (irodsCommands.getIrodsSession().getX509TrustManager() != 
null) {
             trustManagers = new TrustManager[] { irodsCommands
                     .getIrodsSession().getX509TrustManager() };
         }
         try {
             ctx.init(null, trustManagers, null);
         } catch (KeyManagementException e1) {
             log.error("error initializing ssl context:{}", e1);
             throw new JargonRuntimeException("ssl context init 
exception", e1);
         }



If that was set we can start by throwing some add'l logging in there, 
but it essentially shoves that injected trust manager into the ssl 
context init.

MC

**Comment by dkocher** [comment]
The trust manager is set. Refer to this [branch](https://g.iterate.ch/projects/ITERATE/repos/cyberduck/compare/commits?sourceBranch=refs%2Fheads%2Ffeature%2Firods-jargon-pam-authentication&targetBranch=refs%2Fheads%2Fmaster).

**Comment by michael-conway** [comment]
I see the issue...the factory was not obtained from the ssl context.  
Give me a second..

**Comment by michael-conway** [comment]
deploying again as 4.0.2.4-SNAPSHOT, should take about 5 min for tests to finish

**Comment by michael-conway** [comment]
pushed up to maven as 4.0.2.4-SNAPSHOT.  This derives the SSL socket factor from the SSL Context that holds the custom trust manager.  I added logging to my 'accept all' manager and see it activate.

**Comment by dkocher** [comment]
Still having the same stacktrace with `jargon-core-4.0.2.4-20151110.164008-5`.

**Comment by michael-conway** [comment]
Is your trust Mgr firing?

**Comment by dkocher** [comment]
According to the stacktrace this is before the trust manager comes into play. The error is fired from `RODS_API_REQ`.

**Comment by michael-conway** [comment]
OK, well, that's an SSL related error, As I've seen this, it tends to be 

* SSL misconfiguration on the iRODS server (what server are you running against?)

* Handshake errors due to protocol mismatch e.g. SSL or prior TLS on the JDK that isn't up to the latest TLS revs.  iRODS is pretty much committed to the latest versions of TLS due to security concerns, and JDK 1.7 and prior can sometimes not have the required protocols

* I've not tried a custom trust manager, but perhaps there are other considerations/configuration required for self signed certs

**Comment by michael-conway** [comment]
PS for ref, here's the PamAuthTest testPamAuthValid unit test logging that shows a successful connection, so we can compare.  Note that it starts as a normal tcp connection and then once it sees it is PAM is tunnels an SSL connection.  It does this by calling 'startSSL' as an API request to iRODS, and I wonder if that's where things fall down.  That can be things like iRODS not able to read the public and private keys on the server side or other misconfigurations.  It might be useful to see the iRODS logs when this fails...

```
0    [main] INFO  org.irods.jargon.core.connection.IRODSSimpleProtocolManager  - creating simple protocol manager
6    [main] DEBUG org.irods.jargon.core.connection.IRODSSession  - IRODS Session creation, loading default properties, these may be overridden...
9    [main] INFO  org.irods.jargon.core.connection.IRODSSession  - checkInitTrustManager()
9    [main] INFO  org.irods.jargon.core.pub.IRODSFileSystem  - IRODSfileSystem is initialized
19   [main] DEBUG org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl  - creating access object factory
20   [main] DEBUG org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl  - creating access object factory
20   [main] DEBUG org.irods.jargon.core.pub.IRODSGenericAO  - establishing connection
20   [main] DEBUG org.irods.jargon.core.connection.IRODSSession  - no connections are cached, so create a new cache map
22   [main] DEBUG org.irods.jargon.core.connection.IRODSSimpleProtocolManager  - creating an IRODSSimpleConnection for account:irods://mconway@localhost:1247
23   [main] DEBUG org.irods.jargon.core.connection.IRODSProtocolManager  - creating a fresh AbstractIRODSMidLevelProtocol for account:irods://mconway@localhost:1247
23   [main] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - instance() method...calling connection life cycle
23   [main] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - create connection....
23   [main] INFO  org.irods.jargon.core.connection.IRODSTCPConnectionFactoryImpl  - instance()
24   [main] INFO  org.irods.jargon.core.connection.AbstractConnection  - AbstractConnection()
25   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - initializing connection with account:irods://mconway@localhost:1247
25   [main] INFO  org.irods.jargon.core.connection.AbstractConnection  - opening irods socket
25   [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - connect()
25   [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - connecting socket to agent
25   [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - normal iRODS connection
27   [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - connection to socket made...
27   [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - default buffer on input stream
27   [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - default buffer on input stream
27   [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - socket opened successfully
28   [main] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - ...have connection, now authenticate given the auth scheme in the iRODS account...
28   [main] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - authenticate()
28   [main] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - get auth mechanism
28   [main] INFO  org.irods.jargon.core.connection.AuthenticationFactoryImpl  - instanceAuthMechanism()
28   [main] INFO  org.irods.jargon.core.connection.AuthenticationFactoryImpl  - authScheme:PAM
28   [main] INFO  org.irods.jargon.core.connection.AuthenticationFactoryImpl  - using PAM auth
29   [main] INFO  org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory  - authenticate...
30   [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - startupPackData:<StartupPack_PI><irodsProt>1</irodsProt>
<reconnFlag>200</reconnFlag>
<connectCnt>0</connectCnt>
<proxyUser>mconway</proxyUser>
<proxyRcatZone>tempZone</proxyRcatZone>
<clientUser>mconway</clientUser>
<clientRcatZone>tempZone</clientRcatZone>
<relVersion>rods3.2</relVersion>
<apiVersion>d</apiVersion>
<option>iinit</option>
</StartupPack_PI>

30   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - functionID: 0
30   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - header:<MsgHeader_PI><type>RODS_CONNECT</type><msgLen>344</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>0</intInfo></MsgHeader_PI>
33   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - reading message from irods
33   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  4
33   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
33   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 4
77   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  139
77   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
77   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 139
77   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message length:204
77   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - error length:0
78   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - bytesLength:0
78   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - info value:0
78   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message length greater than zero
78   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  204
78   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
78   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 204
78   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message from IRODS read back:<Version_PI><status>0</status>
<relVersion>rods4.2.0</relVersion>
<apiVersion>d</apiVersion>
<reconnPort>20165</reconnPort>
<reconnAddr>mikesubuntu</reconnAddr>
<cookie>1374407301</cookie>
</Version_PI>

80   [main] INFO  org.irods.jargon.core.connection.AuthMechanism  - startup response:StartupResponseData:
   status:0
   relVersion:rods4.2.0
   apiVersion:d
   reconnPort:20165
   reconnAddr:mikesubuntu
   cookie:1374407301
80   [main] INFO  org.irods.jargon.core.connection.AuthMechanism  - startSSL for PAM auth
81   [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - calling irods function with byte array
81   [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - calling irods function with:<sslStartInp_PI><arg0></arg0>
</sslStartInp_PI>

81   [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - api number is:1100
81   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - functionID: 1100
81   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - header:<MsgHeader_PI><type>RODS_API_REQ</type><msgLen>48</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>1100</intInfo></MsgHeader_PI>
81   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - reading message from irods
81   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  4
81   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
81   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 4
83   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  139
84   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
84   [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 139
84   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message length:0
84   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - error length:0
84   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - bytesLength:0
84   [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - info value:0
194  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - getting ssl socket factory
238  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - supported cyphers:TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
250  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - ssl socket created for credential exchage..now connect
250  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - starting SSL handshake
337  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - ssl handshake successful
337  [main] INFO  org.irods.jargon.core.connection.AuthMechanism  - creating secure protcol connection layer
337  [main] INFO  org.irods.jargon.core.connection.AbstractConnection  - AbstractConnection()
337  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - initializing connection with account:irods://mconway@localhost:1247
338  [main] INFO  org.irods.jargon.core.connection.AbstractConnection  - opening irods socket
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - connect()
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - connecting socket to agent
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - normal iRODS connection
338  [HandshakeCompletedNotify-Thread] DEBUG org.irods.jargon.core.connection.AuthMechanism  - Handshake finished!
338  [HandshakeCompletedNotify-Thread] DEBUG org.irods.jargon.core.connection.AuthMechanism  - 	 CipherSuite:TLS_RSA_WITH_AES_256_CBC_SHA256
338  [HandshakeCompletedNotify-Thread] DEBUG org.irods.jargon.core.connection.AuthMechanism  - 	 SessionId [Session-1, TLS_RSA_WITH_AES_256_CBC_SHA256]
338  [HandshakeCompletedNotify-Thread] DEBUG org.irods.jargon.core.connection.AuthMechanism  - 	 PeerHost localhost
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - connection to socket made...
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - default buffer on input stream
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - default buffer on input stream
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - socket opened successfully
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - default buffer on input stream
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - default buffer on input stream
338  [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection  - socket opened successfully
338  [main] INFO  org.irods.jargon.core.connection.AuthMechanism  - carrying over startup pack with server info
338  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - created secureIRODSCommands wrapped around an SSL socket
Sending PamAuthRequest...
338  [main] INFO  org.irods.jargon.core.connection.AuthMechanism  - using eirods pluggable pam auth request
339  [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - calling irods function with byte array
339  [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - calling irods function with:<authPlugReqInp_PI><auth_scheme_>PAM</auth_scheme_>
<context_>a_user=mconway;a_pw=th1s$ucks;a_ttl=0</context_>
</authPlugReqInp_PI>

339  [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - api number is:1201
339  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - functionID: 1201
339  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - header:<MsgHeader_PI><type>RODS_API_REQ</type><msgLen>132</msgLen><errorLen>0</errorLen><bsLen>0</bsLen><intInfo>1201</intInfo></MsgHeader_PI>
339  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - reading message from irods
339  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  4
339  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
339  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 4
395  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  140
395  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
395  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 140
396  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message length:80
396  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - error length:0
396  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - bytesLength:0
396  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - info value:0
396  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message length greater than zero
396  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  80
396  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
396  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 80
397  [main] DEBUG org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol  - message from IRODS read back:<authPlugReqOut_PI><result_>e567245df3effcb126c</result_>
</authPlugReqOut_PI>


'''

**Comment by dkocher** [comment]
I am always testing against `data.iplantcollaborative.org`.

**Comment by michael-conway** [comment]
OK I'll ping those guys and try a pam test from here.  I typically work 
by importing a self signed cert into my keystore, and that is typically 
enough.

**Comment by niravmerchant** [comment]
data.iplantcollaborative.org does not use PAM its all iRODS native Auth
