### ISSUE TITLE
create ticket - confusing error message when parent coll has no access

### ISSUE THREAD

**Issue by trel** [DICE-UNC/jargon#188]
From an (anonymized) iRODS support email:

```
When I don’t have the rights to access a file then I see a strange error message
 
/testZone/test1-projectA/data/original/test2.vcf
 
ERROR [com.example.TerraformSession    ] - cannot create ticket for entity /testZone/test1-projectA/data/original/test2.vcf
org.irods.jargon.core.exception.FileNotFoundException: Unknown collection
            at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:166)
            at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
            at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:235)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
            at org.irods.jargon.core.pub.ProtocolExtensionPointImpl.irodsFunction(ProtocolExtensionPointImpl.java:52)
            at org.irods.jargon.ticket.TicketAdminServiceImpl.createTicket(TicketAdminServiceImpl.java:254)
 
 
When I do the same on the parent folder of this file the exception is much more understandable:
           
/testZone/test1-projectA/data/original
 
org.irods.jargon.core.exception.CatNoAccessException: No access to item in catalog
            at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:178)
            at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
            at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:235)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
            at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:571)
            at org.irods.jargon.core.pub.CollectionAOImpl.setAccessPermissionInherit(CollectionAOImpl.java:1222)
            at org.irods.jargon.ticket.TicketAdminServiceImpl.createTicket(TicketAdminServiceImpl.java:242)
```

**Comment by Shane-Park** [comment]
thx i had same exception and didn't know why.
It was because of lack of authority.
