### ISSUE TITLE
irods + mysql and latin1 charset issues

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#227]
. When I switch jargon to Latin1 in the jargon.properties file, I'm getting different errors around "Incorrect string value" (see irods log with SQL trace on below). So can't even add a property. The other thing we tried was to convert the meta table to UTF-8, but if I remember well (we tried few things....) then some characters like "é" were inserted as "e" in the SQL table (loosing the accent) and other issues came up.

```

Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 sql: bindVar[1]=76303
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 sql: bindVar[2]=testprop2
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 sql: bindVar[3]=???
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 sql: bindVar[4]=
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 sql: bindVar[5]=01486044453
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 sql: bindVar[6]=01486044453
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 sql: insert into R_META_MAIN (meta_id, meta_attr_name, meta_attr_value, meta_attr_unit, create_ts, modify_ts) values (?, ?, ?, ?, ?, ?)
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 result: SQL_ERROR
Feb  2 14:07:33 pid:3999 NOTICE: bindVar[1]=76303
Feb  2 14:07:33 pid:3999 NOTICE: bindVar[2]=testprop2
Feb  2 14:07:33 pid:3999 NOTICE: bindVar[3]=???
Feb  2 14:07:33 pid:3999 NOTICE: bindVar[4]=
Feb  2 14:07:33 pid:3999 NOTICE: bindVar[5]=01486044453
Feb  2 14:07:33 pid:3999 NOTICE: bindVar[6]=01486044453
Feb  2 14:07:33 pid:3999 NOTICE: _cllExecSqlNoResult: SQLExecDirect error: -1 sql:insert into R_META_MAIN (meta_id, meta_attr_name, meta_attr_value, meta_attr_unit, create_ts, modify_ts) values (?, ?, ?, ?, ?, ?)
Feb  2 14:07:33 pid:3999 NOTICE: SQLSTATE: S1010
Feb  2 14:07:33 pid:3999 NOTICE: SQLCODE: 0
Feb  2 14:07:33 pid:3999 NOTICE: SQL Error message: [unixODBC][Driver Manager]Function sequence error
Feb  2 14:07:33 pid:3999 NOTICE: SQLSTATE: S1000
Feb  2 14:07:33 pid:3999 NOTICE: SQLCODE: 1366
Feb  2 14:07:33 pid:3999 NOTICE: SQL Error message: [unixODBC][MySQL][ODBC 5.1 Driver][mysqld-5.5.46-0ubuntu0.12.04.2]Incorrect string value: '\xE1\xE0\xE2' for column 'meta_attr_value' at row 1
Feb  2 14:07:33 pid:3999 NOTICE: findOrInsertAVU insert failure -806000
Feb  2 14:07:33 pid:3999 NOTICE: chlAddAVUMetadata findOrInsertAVU failure -806000
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 sql: rollback
Feb  2 14:07:33 pid:3999 LOG_SQL: pid: 3999 result: SUCCESS
Feb  2 14:07:33 pid:3999 NOTICE: chlAddAVUMetadata cmlExecuteNoAnswerSql(rollback) succeeded
Feb  2 14:07:33 pid:3999 NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
Feb  2 14:07:33 pid:3999 ERROR: [-]    iRODS/server/core/src/rsApiHandler.cpp:470:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
    [-]    iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
        [-]    libtcp.cpp:240:tcp_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]

Feb  2 14:07:33 pid:3999 NOTICE: Agent exiting with status = -4000
Feb  2 14:07:34 pid:11372 NOTICE: Agent process 3999 exited with status 24576
eb  2 14:07:33 pid:3999 NOTICE: SQLSTATE: S1010
Feb  2 14:07:33 pid:3999 NOTICE: SQLCODE: 0
Feb  2 14:07:33 pid:3999 NOTICE: SQL Error message: [unixODBC][Driver Manager]Function sequence error
Feb  2 14:07:33 pid:3999 NOTICE: SQLSTATE: S1000
Feb  2 14:07:33 pid:3999 NOTICE: SQLCODE: 1366
Feb  2 14:07:33 pid:3999 NOTICE: SQL Error message: [unixODBC][MySQL][ODBC 5.1 Driver][mysqld-5.5.46-0ubuntu0.12.04.2]Incorrect string value: '\xE1\xE0\xE2' for column 'meta_attr_value' at row 1
```

**Comment by michael-conway** [comment]
This is a follow-up on the issue below reported a couple of weeks ago around not being able to update metadata properties containing accentuated characters (e.g. éèê) when using iRODS with MySql, and the MySql server/tables are configured with a Latin1 character set (which is the default).

We have published a simple Jargon Java project reproducing the problem with our server. This is available at:
https://bitbucket.org/mtnaus/irods-mysql-encoding-issue
Main source code also attached (but you'll need to checkout from Git repository to compile and run)

The errors we come down to the following errors being reported by MySql ODBC:
Illegal mix of collations (latin1_general_cs,IMPLICIT) and (utf8_general_ci,COERCIBLE)

An underlying issue we uncovered is that iRODS returns AVU values seem to be incorrectly encoded/represented. For example, éèê comes back as ���
This can also be somewhat seen with imeta as follows:
# Create a test collection
imkdir testcoll
imeta add -C testcoll testprop2 éèê
imeta ls -C testcoll
# --> this returns ???
# The value in the r_meta_main MySql table is however correct
The same is seen through Jargon which result in some commands to fail.

We have a platform that is expected to go in production shortly, and this has become a significant issue . We understand that the problem is likely the encoding discrepancy between MySql (Latin1) and iRODS/Jargon (UTF8)

**Comment by michael-conway** [comment]
test code with comments on failing cases

```Java
public static void main( String[] args ) throws JargonException, JargonQueryException
	{
		// init
		ctx = new ClassPathXmlApplicationContext(new String []{"applicationContext.xml"});
		ctx.registerShutdownHook();
		
		irodsFileSystem = (IRODSFileSystem) ctx.getBean("irodsFileSystem");
		irodsAccount = (IRODSAccount) ctx.getBean("irodsAccount");
		irodsAccessObjectFactory = (IRODSAccessObjectFactory) ctx.getBean("irodsAccessObjectFactory");
		irodsFileFactory = irodsFileSystem.getIRODSFileFactory(irodsAccount);
		
		// Get root
		IRODSFile home = irodsFileFactory.instanceIRODSFileUserHomeDir(irodsAccount.getUserName());
		IRODSFile testDir = irodsFileFactory.instanceIRODSFile(home.getAbsolutePath(), "testcoll");
		
		// Clean test directory
		if(testDir.exists()) {
			logger.info("Deleting test directory "+testDir.getAbsolutePath());
			testDir.deleteWithForceOption();
		}
		
		// Create test directory
		logger.info("Creating test directory "+testDir.getAbsolutePath());
		testDir.mkdirs();
		
 		// Get test collection AO
		CollectionAO collectionAO=irodsAccessObjectFactory.getCollectionAO(irodsAccount);
		Collection testCollection = collectionAO.findByAbsolutePath(testDir.getAbsolutePath());
		
		// Add a simple property
		// --> This works  
		logger.info("\nAdding simple property");
		collectionAO.addAVUMetadata(testCollection.getAbsolutePath(),
				new AvuData("testprop1","abcde",""));
		dumpCollectionAvu(collectionAO,testCollection.getAbsolutePath());

		// Add an accentuated property
		// --> This works  
		logger.info("\nAdding accentuated property");
		collectionAO.addAVUMetadata(testCollection.getAbsolutePath(),
				new AvuData("testprop2","áàâ",""));
		// --> The value it the MySql r_meta_main table is áàâ  
		// --> But the returned value is ��� instead of áàâ
		// --> Using the imeta command line also return ???
		dumpCollectionAvu(collectionAO,testCollection.getAbsolutePath());
		
		// Modify the accentuated property
		// --> This works  
		logger.info("\nModifying accentuated property");
		collectionAO.modifyAVUMetadata(testCollection.getAbsolutePath(),
				new AvuData("testprop2","áàâ",""),
				new AvuData("testprop2","éèê",""));
		dumpCollectionAvu(collectionAO,testCollection.getAbsolutePath());
		
		// Modify accentuated property using GivenAttributeAndUnit
		// --> This fails as the delete SQL query is binding/comparing with a value of ���
		// This result in a SQL error:
		// Illegal mix of collations (latin1_general_cs,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
		logger.info("\nModifying accentuated property BasedOnGivenAttributeAndUnit");
		try {
			collectionAO.modifyAvuValueBasedOnGivenAttributeAndUnit(testCollection.getAbsolutePath(),
					new AvuData("testprop2","úùû",""));
		}
		catch(CatalogSQLException e) {
			logger.error("ERROR: "+e.getMessage());
		}
		dumpCollectionAvu(collectionAO,testCollection.getAbsolutePath());

		// Delete accentuated property 
		// --> This works 
		logger.info("\nDeleting accentuated property");
		collectionAO.deleteAVUMetadata(testCollection.getAbsolutePath(),
				new AvuData("testprop2","éèê",""));
		dumpCollectionAvu(collectionAO,testCollection.getAbsolutePath());
		
		
		// The end
		irodsAccessObjectFactory.closeSession();
		irodsFileSystem.close();

	}

```

**Comment by michael-conway** [comment]
We're trying to solve an issue we're encountering when updating resource metadata through Jargon which contains certain accentuated characters.
This is with Jargon 4.0.2. / iRODS 4.1.7 / MySql 5.5.4.6 on Ubuntu, and having similar problem on a prod server with iRODS 4.1.9  / MySQL 5.1.73 on RHEL.

Basically we seem to be able to insert new metadata values such as "teèéêëst" without any problem, but we we try to update to for example "test", we see a Jargon SQL error in the logs (see below) whereby the "delete" operation fails as a like statements complains about  a mix of collations.

Now noted that Jargon is configured to use UTF-8 but the underlying MySql database icat database and tables have encoding set to latin1/ latin1_general_cs
We tried to:
(1) changed the icat / table settings to utf8mb4/  utf8mb4_unicode_ci (using alter table ... convert SQL command)
(2) changed the icat / table settings to utf8 /  utf8_general_ci (using alter table ... convert SQL command)
(3) set Jargon to ISO-8859-1
but these do not seem to solve the issue and resulted in other errors or discrepancies.
With utf8 / utf8_general_ci, some change seem to go through without any error, but the underlying database values are actualy not updated.

Is this a known issue? Is there a check list of "settings" you could provide us for MySQL (in particular) as well as icat, jargon, odbc, iRODS, etc.?
Something is misconfigured but can't seem to find away to fix it. Any suggestion would be appreciated.

best
*P

Java logs example:

```
2017-01-12 23:03:10,788 [TP-Processor7] ERROR org.irods.jargon.core.pub.CollectionAOImpl - jargon exception modifying AVU metadata
org.irods.jargon.core.exception.CatalogSQLException: Catalog SQL error
        at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:190)
        at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
        at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:235)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:571)
        at org.irods.jargon.core.pub.CollectionAOImpl.modifyAVUMetadata(CollectionAOImpl.java:732)
        at org.irods.jargon.core.pub.CollectionAOImpl.modifyAvuValueBasedOnGivenAttributeAndUnit(CollectionAOImpl.java:689)
    ...
```

iRODS logs

```
    Jan 13 02:48:26 pid:28667 NOTICE: Warning, pending SQL at cllDisconnect, count: 6
    Jan 13 02:48:26 pid:28667 NOTICE: Warning, pending SQL: begin ...
    Jan 13 02:48:26 pid:28667 NOTICE: Warning, pending SQL: SET SESSION autocommit=0 ...
    Jan 13 02:48:26 pid:28667 NOTICE: Warning, pending SQL: SET SESSION sql_mode='ANSI,ST ...
    Jan 13 02:48:26 pid:28667 NOTICE: Warning, pending SQL: SET character_set_client = ut ...
    Jan 13 02:48:26 pid:28667 NOTICE: Warning, pending SQL: SET character_set_results = u ...
    Jan 13 02:48:26 pid:28667 NOTICE: Agent exiting with status = 0
    Jan 13 02:48:26 pid:25427 NOTICE: Agent process 28667 exited with status 0
    Jan 13 02:48:26 pid:25427 NOTICE: Agent process 28669 started for puser=rods and cuser=rods from 68.57.116.108
    Jan 13 02:48:27 pid:28669 NOTICE: chlDeleteAVUMetadata cmlExecuteNoAnswerSql delete failure -819000
    Jan 13 02:48:27 pid:28669 NOTICE: chlDeleteAVUMetadata cmlExecuteNoAnswerSql(rollback) succeeded
    Jan 13 02:48:27 pid:28669 NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
    Jan 13 02:48:27 pid:28669 NOTICE: bindVar[1]=76120
    Jan 13 02:48:27 pid:28669 NOTICE: bindVar[2]=http://mtna.us/model/core/properties#name?language=fr+type=preferred
    Jan 13 02:48:27 pid:28669 NOTICE: bindVar[3]=t�st
    Jan 13 02:48:27 pid:28669 NOTICE: bindVar[4]=
    Jan 13 02:48:27 pid:28669 NOTICE: _cllExecSqlNoResult: SQLExecDirect error: -1 sql:delete from R_OBJT_METAMAP where object_id=? and meta_id IN (select meta_id from R_META_MAIN where meta_attr_name = ? and meta_attr_value = ? and (meta_attr_unit = ? or meta_attr_unit IS NULL) )
    Jan 13 02:48:27 pid:28669 NOTICE: SQLSTATE: S1010
    Jan 13 02:48:27 pid:28669 NOTICE: SQLCODE: 0
    Jan 13 02:48:27 pid:28669 NOTICE: SQL Error message: [unixODBC][Driver Manager]Function sequence error
    Jan 13 02:48:27 pid:28669 NOTICE: SQLSTATE: S1000
    Jan 13 02:48:27 pid:28669 NOTICE: SQLCODE: 1267
    Jan 13 02:48:27 pid:28669 NOTICE: SQL Error message: [unixODBC][MySQL][ODBC 5.1 Driver][mysqld-5.5.46-0ubuntu0.12.04.2]Illegal mix of collations (latin1_general_cs,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
    Jan 13 02:48:27 pid:28669 NOTICE: chlDeleteAVUMetadata cmlExecuteNoAnswerSql delete failure -806000
    Jan 13 02:48:27 pid:28669 NOTICE: chlModAVUMetadata cmlExecuteNoAnswerSql(rollback) succeeded
    Jan 13 02:48:27 pid:28669 NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
    Jan 13 02:48:27 pid:28669 NOTICE: readAndProcClientMsg: received disconnect msg from client
    Jan 13 02:48:27 pid:28669 NOTICE: Agent exiting with status = 0
    Jan 13 02:48:27 pid:25427 NOTICE: Agent process 28669 exited with status 0
    Jan 13 02:48:27 pid:25427 NOTICE: Agent process 28671 started for puser=rods and cuser=rods from 68.57.116.108
    Jan 13 02:48:27 pid:28671 NOTICE: bindVar[1]=76120
    Jan 13 02:48:27 pid:28671 NOTICE: bindVar[2]=http://mtna.us/model/core/properties#name?language=fr+type=preferred
    Jan 13 02:48:27 pid:28671 NOTICE: bindVar[3]=t�st
    Jan 13 02:48:27 pid:28671 NOTICE: bindVar[4]=
    Jan 13 02:48:27 pid:28671 NOTICE: _cllExecSqlNoResult: SQLExecDirect error: -1 sql:delete from R_OBJT_METAMAP where object_id=? and meta_id IN (select meta_id from R_META_MAIN where meta_attr_name like ? and meta_attr_value like ? and (meta_attr_unit like ? or meta_attr_unit IS NULL) )
    Jan 13 02:48:27 pid:28671 NOTICE: SQLSTATE: S1010
    Jan 13 02:48:27 pid:28671 NOTICE: SQLCODE: 0
    Jan 13 02:48:27 pid:28671 NOTICE: SQL Error message: [unixODBC][Driver Manager]Function sequence error
    Jan 13 02:48:27 pid:28671 NOTICE: SQLSTATE: S1000
    Jan 13 02:48:27 pid:28671 NOTICE: SQLCODE: 1267
    Jan 13 02:48:27 pid:28671 NOTICE: SQL Error message: [unixODBC][MySQL][ODBC 5.1 Driver][mysqld-5.5.46-0ubuntu0.12.04.2]Illegal mix of collations (latin1_general_cs,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'like'
    Jan 13 02:48:27 pid:28671 NOTICE: chlDeleteAVUMetadata cmlExecuteNoAnswerSql delete failure -806000
    Jan 13 02:48:27 pid:28671 NOTICE: chlDeleteAVUMetadata cmlExecuteNoAnswerSql(rollback) succeeded
    Jan 13 02:48:27 pid:28671 NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
    Jan 13 02:48:28 pid:28671 NOTICE: readAndProcClientMsg: received disconnect msg from client

```

**Comment by michael-conway** [comment]
appears to also occur in icommands

```
mconway@mikesubuntu:~/.irods$ imeta add -d testBulkAddAVUMetadataToDataObjectSpecialCharsBug227.txt icommand áàâ
mconway@mikesubuntu:~/.irods$ imeta ls -d testBulkAddAVUMetadataToDataObjectSpecialCharsBug227.txt 
AVUs defined for dataObj testBulkAddAVUMetadataToDataObjectSpecialCharsBug227.txt:
attribute: testBulkAddAVUMetadataToDataObject
value: ���
units: 
----
attribute: icommand
value: ���
units: 


```

**Comment by michael-conway** [comment]
the test passes if postgres is the database

```
mconway@mikesubuntu:~/.irods$ imeta ls -d testBulkAddAVUMetadataToDataObjectSpecialCharsBug227.txt
AVUs defined for dataObj testBulkAddAVUMetadataToDataObjectSpecialCharsBug227.txt:
attribute: testBulkAddAVUMetadataToDataObject
value: áàâ
units: 


```

**Comment by michael-conway** [comment]
mysql info

https://dev.mysql.com/doc/refman/5.7/en/charset-repertoire.html

The ASCII range is a subset of UNICODE range, so a string with ASCII repertoire can be converted safely without loss of information to the character set of any string with UNICODE repertoire or to a character set that is a superset of ASCII. (All MySQL character sets are supersets of ASCII with the exception of swe7, which reuses some punctuation characters for Swedish accented characters.) The use of repertoire enables character set conversion in expressions for many cases where MySQL would otherwise return an “illegal mix of collations” error.

**Comment by michael-conway** [comment]
looking at mysql the data is stored correctly

```
mysql> SELECT * FROM R_META_MAIN;
+---------+----------------+------------------------------------+-----------------+----------------+-----------+-------------+-------------+
| meta_id | meta_namespace | meta_attr_name                     | meta_attr_value | meta_attr_unit | r_comment | create_ts   | modify_ts   |
+---------+----------------+------------------------------------+-----------------+----------------+-----------+-------------+-------------+
|   10037 | NULL           | testBulkAddAVUMetadataToDataObject | áàâ             |                | NULL      | 01486406999 | 01486406999 |
|   10043 | NULL           | icommand                           | áàâ             |                | NULL      | 01486408075 | 01486408075 |
+---------+----------------+------------------------------------+-----------------+----------------+-----------+-------------+-------------+
2 rows in set (0.00 sec)


```

**Comment by michael-conway** [comment]
From ben..


In the file /var/lib/irods/.odbc.ini, can you add the entry Charset=UTF8 and see if that works? With that entry, I am able to do all the following without error:

imeta add -d VERSION.json attribute2 éèê
imeta ls -d VERSION.json
imeta rm -d VERSION.json attribute2 éèê


For reference, my modified /var/lib/irods/.odbc.ini looks like:

    [mysql]
    Driver=/usr/lib/x86_64-linux-gnu/odbc/libmyodbc.so
    Database=ICAT
    Server=localhost
    Option=2

**Comment by michael-conway** [comment]
I will close this, and additional discussions should probably be done in the iRODS github space.  We do plan a database testing sprint with Jargon over the next few weeks to help reveal any remaining issues!
