### ISSUE TITLE
Parallel file transfer does not work

### ISSUE THREAD

**Issue by JWollnik** [DICE-UNC/jargon#228]
The parallel file transfer is broken in 4.1.10.0-RC2. 

The following exception occurs for large files (in this case 1,3GB);

```
17:42:34.080 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - ===========================
17:42:34.080 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - ptr:4191660
17:42:34.080 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - myLength:2692
17:42:34.081 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - >>> read:2692
17:42:34.081 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - total read now:4194352
17:42:34.081 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - out of original length:4194352
17:42:34.081 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - makes my length:0
17:42:34.081 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.encrypt.ParallelDecryptionCipherWrapper - decrypt
17:42:34.081 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper - doDecrypt()
17:42:34.081 [pool-1-thread-8] DEBUG org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper - fullbuffer length:4194352
17:42:34.081 [pool-1-thread-8] DEBUG org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper - buffer - iv length:4194320
17:42:34.083 [pool-1-thread-8] DEBUG org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper - length of encrypted buffer:4194320
17:42:34.083 [pool-1-thread-8] ERROR org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper - error during encryption
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:102)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:141)
	at org.irods.jargon.core.transfer.encrypt.ParallelDecryptionCipherWrapper.decrypt(ParallelDecryptionCipherWrapper.java:59)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:308)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:197)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:161)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17:42:34.083 [pool-1-thread-8] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread - exception in parallel transfer
org.irods.jargon.core.exception.JargonRuntimeException: Unable to decrypt given negotiated settings
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:112)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:141)
	at org.irods.jargon.core.transfer.encrypt.ParallelDecryptionCipherWrapper.decrypt(ParallelDecryptionCipherWrapper.java:59)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:308)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:197)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:161)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:102)
	... 10 common frames omitted
17:42:34.085 [pool-1-thread-8] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread - a jargon exception occurred in the get loop
17:42:34.085 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - parallel thread closing out local random access file stream
17:42:34.085 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - closing sockets, this close eats exceptions
17:42:34.086 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - closing local file
17:42:34.086 [pool-1-thread-8] INFO org.irods.jargon.core.transfer.ParallelGetTransferThread - local file closed, exiting get() method
17:42:34.086 [pool-1-thread-8] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread - unchecked exception in transfer
org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:406)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:197)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:161)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.irods.jargon.core.exception.JargonRuntimeException: Unable to decrypt given negotiated settings
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:112)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:141)
	at org.irods.jargon.core.transfer.encrypt.ParallelDecryptionCipherWrapper.decrypt(ParallelDecryptionCipherWrapper.java:59)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:308)
	... 7 common frames omitted
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:102)
	... 10 common frames omitted
17:42:34.086 [main] ERROR org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy - an error occurred in a parallel get
org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy.transferWithExecutor(ParallelGetFileTransferStrategy.java:180)
	at org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy.transfer(ParallelGetFileTransferStrategy.java:146)
	at org.irods.jargon.core.pub.DataObjectAOImpl.checkNbrThreadsAndProcessAsParallelIfMoreThanZeroThreads(DataObjectAOImpl.java:1710)
	at org.irods.jargon.core.pub.DataObjectAOImpl.processGetAfterResourceDetermined(DataObjectAOImpl.java:1527)
	at org.irods.jargon.core.pub.DataObjectAOImpl.getDataObjectFromIrods(DataObjectAOImpl.java:1162)
	at org.irods.jargon.core.pub.TransferOperationsHelper.processGetOfSingleFile(TransferOperationsHelper.java:333)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.processGetAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:557)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.getOperation(DataTransferOperationsImpl.java:315)
	at genedata.rfs.mount.Test.main(Test.java:40)
Caused by: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:175)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:406)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:197)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:161)
	... 5 common frames omitted
Caused by: org.irods.jargon.core.exception.JargonRuntimeException: Unable to decrypt given negotiated settings
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:112)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:141)
	at org.irods.jargon.core.transfer.encrypt.ParallelDecryptionCipherWrapper.decrypt(ParallelDecryptionCipherWrapper.java:59)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:308)
	... 7 common frames omitted
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:102)
	... 10 common frames omitted
17:42:34.087 [main] ERROR org.irods.jargon.core.pub.DataObjectAOImpl - exception in parallel transfer, connection will be abandoned
org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy.transferWithExecutor(ParallelGetFileTransferStrategy.java:191)
	at org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy.transfer(ParallelGetFileTransferStrategy.java:146)
	at org.irods.jargon.core.pub.DataObjectAOImpl.checkNbrThreadsAndProcessAsParallelIfMoreThanZeroThreads(DataObjectAOImpl.java:1710)
	at org.irods.jargon.core.pub.DataObjectAOImpl.processGetAfterResourceDetermined(DataObjectAOImpl.java:1527)
	at org.irods.jargon.core.pub.DataObjectAOImpl.getDataObjectFromIrods(DataObjectAOImpl.java:1162)
	at org.irods.jargon.core.pub.TransferOperationsHelper.processGetOfSingleFile(TransferOperationsHelper.java:333)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.processGetAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:557)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.getOperation(DataTransferOperationsImpl.java:315)
	at genedata.rfs.mount.Test.main(Test.java:40)
Caused by: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy.transferWithExecutor(ParallelGetFileTransferStrategy.java:180)
	... 8 common frames omitted
Caused by: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:175)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:406)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:197)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:161)
	... 5 common frames omitted
Caused by: org.irods.jargon.core.exception.JargonRuntimeException: Unable to decrypt given negotiated settings
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:112)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:141)
	at org.irods.jargon.core.transfer.encrypt.ParallelDecryptionCipherWrapper.decrypt(ParallelDecryptionCipherWrapper.java:59)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:308)
	... 7 common frames omitted
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper.doDecrypt(AesCipherDecryptWrapper.java:102)
	... 10 common frames omitted
17:42:34.088 [main] DEBUG org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl - creating access object factory
17:42:34.088 [main] WARN org.irods.jargon.core.connection.IRODSSession - discarding irods session for: irods://username@dev:1247
17:42:34.088 [main] WARN org.irods.jargon.core.connection.IRODSProtocolManager - connection returned with IOException, will forcefully close and remove from session cache
17:42:34.088 [main] WARN org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol - obliterateConnectionAndDiscardErrors() will forcefully close the connection
17:42:34.088 [main] DEBUG org.irods.jargon.core.connection.IRODSBasicTCPConnection - is connected for : IRODSBasicTCPConnection []
```

iRODS Log:

```
Feb  7 16:23:16 pid:21355 NOTICE: Agent process 35847 exited with status 16384
Feb  7 16:23:19 pid:21355 NOTICE: Agent process 36236 started for puser=username and cuser=username from 172.20.144.85
Authenticated
Feb  7 16:23:21 pid:36236 NOTICE: readAndProcClientMsg: received disconnect msg from client
Feb  7 16:23:21 pid:36236 NOTICE: Agent exiting with status = 0
Feb  7 16:23:21 pid:21355 NOTICE: Agent process 36251 started for puser=username and cuser=username from 172.20.144.85
Feb  7 16:23:22 pid:21355 NOTICE: Agent process 36236 exited with status 0
Feb  7 16:23:22 pid:36251 NOTICE: _partialDataGet:Bytes written 2955264 don't match read 4194304
Feb  7 16:23:22 pid:36251 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Feb  7 16:23:22 pid:36251 ERROR: sendTranHeader: toWrite = 24, written = 0
Feb  7 16:23:22 pid:36251 NOTICE: _partialDataGet:Bytes written 2175624 don't match read 4194304
Feb  7 16:23:22 pid:36251 NOTICE: _partialDataGet:Bytes written 2235484 don't match read 4194304
Feb  7 16:23:22 pid:36251 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Feb  7 16:23:22 pid:36251 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Feb  7 16:23:22 pid:36251 ERROR: sendTranHeader: toWrite = 24, written = 0
Feb  7 16:23:22 pid:36251 ERROR: sendTranHeader: toWrite = 24, written = 0
Feb  7 16:23:22 pid:36251 NOTICE: _partialDataGet:Bytes written 2108464 don't match read 4194304
Feb  7 16:23:22 pid:36251 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Feb  7 16:23:22 pid:36251 ERROR: sendTranHeader: toWrite = 24, written = 0
Feb  7 16:23:22 pid:36251 NOTICE: _partialDataGet:Bytes written 2333304 don't match read 4194304
Feb  7 16:23:22 pid:36251 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Feb  7 16:23:22 pid:36251 ERROR: sendTranHeader: toWrite = 24, written = 0
Feb  7 16:23:22 pid:36251 NOTICE: _partialDataGet:Bytes written 2128904 don't match read 4194304
Feb  7 16:23:22 pid:36251 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Feb  7 16:23:22 pid:36251 ERROR: sendTranHeader: toWrite = 24, written = 0
Feb  7 16:23:22 pid:36251 NOTICE: _partialDataGet:Bytes written 2095100 don't match read 4194304
Feb  7 16:23:22 pid:36251 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Feb  7 16:23:22 pid:36251 ERROR: sendTranHeader: toWrite = 24, written = 0
Feb  7 16:23:22 pid:36251 NOTICE: _partialDataGet:Bytes written 2117000 don't match read 4194304
Feb  7 16:23:22 pid:36251 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Feb  7 16:23:22 pid:36251 ERROR: sendTranHeader: toWrite = 24, written = 0
Feb  7 16:23:22 pid:36251 ERROR: [-]    iRODS/server/core/src/rsApiHandler.cpp:470:readAndProcClientMsg :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message []
        [-]     iRODS/lib/core/src/sockComm.cpp:199:readMsgHeader :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']
                [-]     libssl.cpp:583:ssl_read_msg_header :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [read 0 expected 4]
```

The transfer works fine for small files or if the negotiation policy has been set to ClientServerNegotiationPolicy.SslNegotiationPolicy.NO_NEGOTIATION.

Here's a code snippet to reproduce the issue (which worked with 4.0.2.6-RELEASE):

```
public static void main(String[] args) throws JargonException {
		IRODSFileSystem fs = null;
		File targetLocalFile = null;
		try {
			fs = IRODSFileSystem.instance();
			IRODSSession session = fs.getIrodsSession();
			SettableJargonProperties props = new SettableJargonProperties(session.getJargonProperties());
//			props.setNegotiationPolicy(ClientServerNegotiationPolicy.SslNegotiationPolicy.NO_NEGOTIATION);
			session.setJargonProperties(props);
			session.setX509TrustManager(SSL.getTrustManager());
			IRODSAccount account = createIrodsAccount(args);
			account.setAuthenticationScheme(AuthScheme.PAM);
			IRODSAccessObjectFactory f = fs.getIRODSAccessObjectFactory();
			f.authenticateIRODSAccount(account);
			IRODSFile srcRemotefile = f.getIRODSFileFactory(account).instanceIRODSFile("/path/to/large/file");
			DataTransferOperations dataTransferOperations = fs.getIRODSAccessObjectFactory().getDataTransferOperations(account);
			targetLocalFile = new File(new File("/tmp"), srcRemotefile.getName());
			dataTransferOperations.getOperation(srcRemotefile, targetLocalFile, new TransferStatusCallbackListener() {
					@Override
					public FileStatusCallbackResponse statusCallback(TransferStatus transferStatus) throws JargonException { return null; }
					@Override
					public void overallStatusCallback(TransferStatus transferStatus) throws JargonException { }
					@Override
					public CallbackResponse transferAsksWhetherToForceOperation(String irodsAbsolutePath, boolean isCollection) { return CallbackResponse.CANCEL; }
				},
				null);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (fs != null) {
				fs.close();
			}
			if (targetLocalFile!=null && targetLocalFile.exists()) {
				System.out.println("Download deleted: " + targetLocalFile.delete());
			}
			System.runFinalization();
			System.gc();
		}
	}
```

**Comment by michael-conway** [comment]
Will add a test, may have to do with the no-negotiation setting.

A quick test in the mean time might be to set jargon properties to CS_NEG_DONT_CARE on the client and I suspect it will resolve the problem temporarily.

**Comment by JWollnik** [comment]
Hi Michael,

the transfer works for large files ONLY if the negotiation policy has been set to ClientServerNegotiationPolicy.SslNegotiationPolicy.NO_NEGOTIATION. If we use the default CS_NEG_DONT_CARE, then it does NOT work. Maybe you overlooked that in the above example the negotation policy setting is commented out :)

**Comment by michael-conway** [comment]
OK my bad ;-) 

Running tests now..

**Comment by michael-conway** [comment]
Initial test fails to replicate....will review further

**Comment by JWollnik** [comment]
I added the iRODs log messages to my first post.

**Comment by michael-conway** [comment]
here's the test I'm running. In this case, it's PAM + SSL Neg don't care (which takes the server defaults)

This is the 4.1.10.0-SNAPSHOT at the HEAD of master, and in Maven

This is against iRODS 4.2 ssl configured.  

I'm focused on the error, IllegalKeySize...I did find this..

http://stackoverflow.com/questions/3862800/invalidkeyexception-illegal-key-size.  This makes me think this isn't really about the parallel transfer per se, but rather about the AES key size used in relation to the capabilities of the JVM you are running on, etc.  

The encryption params are in /var/lib/irods/.irods/irods_environment.json

Here's what I have...

```json


{
    "irods_client_server_negotiation": "request_server_negotiation",
    "irods_client_server_policy": "CS_NEG_REQUEST",
    "irods_cwd": "/zone1/home/rods",
    "irods_default_hash_scheme": "SHA256",
    "irods_default_number_of_transfer_threads": 4,
    "irods_default_resource": "test1-resc",
    "irods_encryption_algorithm": "AES-256-CBC",
    "irods_encryption_key_size": 32,
    "irods_encryption_num_hash_rounds": 16,
    "irods_encryption_salt_size": 8,
    "irods_home": "/zone1/home/rods",
    "irods_host": "irods420.irodslocal",
    "irods_match_hash_policy": "compatible",
    "irods_maximum_size_for_single_buffer_in_megabytes": 32,
    "irods_port": 1247,
    "irods_server_control_plane_encryption_algorithm": "AES-256-CBC",
    "irods_server_control_plane_encryption_num_hash_rounds": 16,
    "irods_server_control_plane_key": "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
    "irods_server_control_plane_port": 1248,
    "irods_transfer_buffer_size_for_parallel_transfer_in_megabytes": 4,
    "irods_ssl_certificate_chain_file": "/etc/irods/ssl/server.crt",
    "irods_ssl_certificate_key_file": "/etc/irods/ssl/server.key",
    "irods_ssl_dh_params_file": "/etc/irods/ssl/dhparams.pem",
    "irods_ssl_verify_server": "none",
    "irods_user_name": "rods",
    "irods_zone_name": "zone1",
    "schema_name": "irods_environment",
    "schema_version": "v3"
}










```
Can you eyeball your settings there?  What jvm are you using?  Is this iRODS 4.2?  

Can we test using the 4.1.10.0-SNAPSHOT so we're on the same page?  We can also pull this out of the parallel encryption code and test the AES round trip using something like this...

https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/test/java/org/irods/jargon/core/transfer/encrypt/AesCipherDecryptWrapperTest.java


```Java

/**
	 * Test for https://github.com/DICE-UNC/jargon/issues/228
	 * 
	 * @throws JargonException
	 * @throws TestingUtilsException
	 * @throws IRODSTestAssertionException
	 */
	@Test
	public void testParallelTransferSetNoNegotiationBug228()
			throws JargonException, TestingUtilsException,
			IRODSTestAssertionException {

		/*
		 * Only run if ssl enabled
		 */
		if (!testingPropertiesHelper.isTestSsl(testingProperties)) {
			return;
		}

		/*
		 * Only run if pam enabled
		 */
		if (!testingPropertiesHelper.isTestPAM(testingProperties)) {
			return;
		}

		IRODSAccount irodsAccount = testingPropertiesHelper
				.buildPamIrodsAccountFromTestProperties(testingProperties);
		irodsAccount.setAuthenticationScheme(AuthScheme.PAM);

		SettableJargonProperties settableJargonProperties = new SettableJargonProperties(
				irodsFileSystem.getJargonProperties());
		settableJargonProperties
				.setNegotiationPolicy(SslNegotiationPolicy.CS_NEG_DONT_CARE);
		settableJargonProperties.setComputeAndVerifyChecksumAfterTransfer(true);
		irodsFileSystem.getIrodsSession().setJargonProperties(
				settableJargonProperties);

		long length = 2l * 1024l * 1024l * 1024l;
		String testFileName = "testParallelTransferSetNoNegotiationBug228.txt";
		String returnedTestFileName = "testParallelTransferSetNoNegotiationBug228Get.txt";
		String absPath = scratchFileUtils
				.createAndReturnAbsoluteScratchPath(IRODS_TEST_SUBDIR_PATH);
		String localFileName = FileGenerator
				.generateFileOfFixedLengthGivenName(absPath, testFileName,
						length);

		String targetIrodsPath = testingPropertiesHelper
				.buildIRODSCollectionAbsolutePathFromPamTestProperties(
						testingProperties, IRODS_TEST_SUBDIR_PATH + '/'
								+ testFileName);

		IRODSFile collFile = irodsFileSystem.getIRODSAccessObjectFactory()
				.getIRODSFileFactory(irodsAccount)
				.instanceIRODSFile(targetIrodsPath);
		IRODSFile parentFile = (IRODSFile) collFile.getParentFile();
		parentFile.delete();
		parentFile.mkdirs();
		DataTransferOperations dataTransferOperationsAO = irodsFileSystem
				.getIRODSAccessObjectFactory().getDataTransferOperations(
						irodsAccount);

		dataTransferOperationsAO.putOperation(localFileName, targetIrodsPath,
				"", null, null);

		File getFile = new File(absPath, returnedTestFileName);
		File getFileParent = getFile.getParentFile();
		getFileParent.delete();
		getFileParent.mkdirs();
		dataTransferOperationsAO.getOperation(targetIrodsPath,
				getFile.getAbsolutePath(), "", null, null);

		// checksum verification is in place, so no error = success

	}


```

**Comment by JWollnik** [comment]
Hi Mike,

somehow the code snippet used no SSL for parallel data transfer with 4.0.2.6-RELEASE and it used SSL for parallel data transfer with 4.1.10.0-RC2. In combination with using a JVM without Java Cryptography Extension we observed the above error for 4.1.10.0-RC2.

So I guess you can close the issue. Thanks for looking into this.

Best, Johannes

**Comment by michael-conway** [comment]
Yes, the 4.1.10.0 was the release point where the ssl transport support was introduced.  4.0.2.6 did not have this feature.

You can, if need be, set the core.re of your irods server to ssl_neg_refuse if you want to shut off the ssl behavior.  

Thanks so much with testing this out and getting back, please let me know how it's going!
