### ISSUE TITLE
PAM authentication error produces POTENTIAL CONNECTION LEAK error

### ISSUE THREAD

**Issue by JWollnik** [DICE-UNC/jargon#256]
If I am using Jargon 4.1.10.0 with wrong credentials, then I will get this "PAM authentication error" exception:

```
org.irods.jargon.core.exception.AuthenticationException: PAM authentication error
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:208)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1232)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:724)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:690)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:220)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:176)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:572)
	at org.irods.jargon.core.connection.PAMAuth.processAuthenticationAfterStartup(PAMAuth.java:69)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:217)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:241)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:103)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:146)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:69)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:511)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:400)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:81)
```

This it totally okay, unfortunately it produces a POTENTIAL CONNECTION LEAK error message in the logs when the AbstractConnection object is garbage collected:

```
[Finalizer] ERROR org.irods.jargon.core.connection.AbstractConnection - **************************************************************************************
[Finalizer] ERROR org.irods.jargon.core.connection.AbstractConnection - ********  WARNING: POTENTIAL CONNECTION LEAK  ******************
[Finalizer] ERROR org.irods.jargon.core.connection.AbstractConnection - ********  finalizer has run and found a connection left opened, please check your code to ensure that all connections are closed
[Finalizer] ERROR org.irods.jargon.core.connection.AbstractConnection - ********  connection is:irods://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX, will attempt to disconnect
[Finalizer] ERROR org.irods.jargon.core.connection.AbstractConnection - **************************************************************************************
```

This code snippet should be sufficient to reproduce the issue when using wrong credentials:

```
public static void main(String[] args) throws JargonException {
		IRODSFileSystem fs = null;
		try {
			fs = IRODSFileSystem.instance();
			IRODSSession session = fs.getIrodsSession();
			session.setX509TrustManager(SSL.getTrustManager());
			IRODSAccount account = createIrodsAccount(args);
			account.setAuthenticationScheme(AuthScheme.PAM);
			IRODSAccessObjectFactory f = fs.getIRODSAccessObjectFactory();
			f.authenticateIRODSAccount(account);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (fs != null) {
				fs.close();
			}
			System.gc();
			System.runFinalization();
		}
	}
```

**Comment by michael-conway** [comment]
testing this, but NB that message is issued at the time that any remaining connections are closed, so it wouldn't leak.  I'll see if there is a way to more gracefully handle this tho...
