### ISSUE TITLE
Illegal key size exceptions on AES encryption tests on Windows

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#260]
example log from unit tests on windows

```
0    [main] INFO  org.irods.jargon.core.transfer.encrypt.AESKeyGenerator  - generateKey()
6182 [main] INFO  org.irods.jargon.core.transfer.encrypt.AesCipherDecryptWrapper  - initCipher()
6189 [main] INFO  org.irods.jargon.core.transfer.encrypt.AESKeyGenerator  - generateKey()
6190 [main] INFO  org.irods.jargon.core.transfer.encrypt.AesCipherEncryptWrapper  - initCipher()
6379 [main] ERROR org.irods.jargon.core.transfer.encrypt.AesCipherEncryptWrapper  - error generating key for cipher
java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at org.irods.jargon.core.transfer.encrypt.AesCipherEncryptWrapper.initImplementation(AesCipherEncryptWrapper.java:83)
	at org.irods.jargon.core.transfer.encrypt.AesCipherEncryptWrapper.<init>(AesCipherEncryptWrapper.java:65)
	at org.irods.jargon.core.transfer.encrypt.EncryptionWrapperFactory.instanceEncrypt(EncryptionWrapperFactory.java:57)
	at org.irods.jargon.core.transfer.encrypt.EncryptionWrapperFactoryTest.testGetAesEncryptFromFactory(EncryptionWrapperFactoryTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)




```

see
https://stackoverflow.com/questions/6481627/java-security-illegal-key-size-or-default-parameters

**Comment by michael-conway** [comment]
policy files here http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html need to be downloaded to jre lib security

**Comment by michael-conway** [comment]
unzip those jars and replace the existing ones in your jre and this solves the issues
