### ISSUE TITLE
Jargon Core tests fail when trying to delete a collection

### ISSUE THREAD

**Issue by korydraughn** [DICE-UNC/jargon#305]
The following two tests consistently fail against iRODS v4.2.2+.  Ignoring these two tests allow the suite to pass.
```
973418 [main] DEBUG org.irods.jargon.core.connection.IRODSSession  - closing all irods sessions
973418 [main] WARN  org.irods.jargon.core.connection.IRODSSession  - closing session that is already closed, silently ignore
Tests run: 1557, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 973.779 sec <<< FAILURE! - in org.irods.jargon.core.unittest.AllTests
testDeleteCollNoForceBug216(org.irods.jargon.core.pub.io.IRODSFileImplTest)  Time elapsed: 1.573 sec  <<< ERROR!
org.irods.jargon.core.exception.JargonRuntimeException: exception occurred on delete
        at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:105)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1275)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:761)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:727)
        at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:215)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:173)
        at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.directoryDeleteNoForce(IRODSFileSystemAOImpl.java:1088)
        at org.irods.jargon.core.pub.io.IRODSFileImpl.delete(IRODSFileImpl.java:391)
        at org.irods.jargon.core.pub.io.IRODSFileImplTest.testDeleteCollNoForceBug216(IRODSFileImplTest.java:1134)

testDeleteACollectionWithAFileWithQuotesInLongerFileName(org.irods.jargon.core.pub.io.IRODSFileImplTest)  Time elapsed: 0.178 sec  <<< ERROR!
org.irods.jargon.core.exception.JargonRuntimeException: exception occurred on delete
        at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:105)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1275)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:761)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:727)
        at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:215)
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:173)
        at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.directoryDeleteNoForce(IRODSFileSystemAOImpl.java:1088)
        at org.irods.jargon.core.pub.io.IRODSFileImpl.delete(IRODSFileImpl.java:391)
        at org.irods.jargon.core.pub.io.IRODSFileImplTest.testDeleteACollectionWithAFileWithQuotesInLongerFileName(IRODSFileImplTest.java:548)


Results :

Tests in error: 
  IRODSFileImplTest.testDeleteCollNoForceBug216:1134 » JargonRuntime exception o...
  IRODSFileImplTest.testDeleteACollectionWithAFileWithQuotesInLongerFileName:548 » JargonRuntime

Tests run: 1557, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Jargon ............................................. SUCCESS [  0.413 s]
[INFO] Jargon Core ........................................ FAILURE [16:21 min]
[INFO] Jargon User Tagging ................................ SKIPPED
[INFO] Jargon Data Utils .................................. SKIPPED
[INFO] Jargon Ticket ...................................... SKIPPED
[INFO] Jargon Pool ........................................ SKIPPED
[INFO] User Profile Service ............................... SKIPPED
[INFO] Jargon Rule Service ................................ SKIPPED
[INFO] data-profile ....................................... SKIPPED
[INFO] jargon-zipservice .................................. SKIPPED
[INFO] Jargon Metadata Query .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16:22 min
[INFO] Finished at: 2018-06-26T08:55:07-04:00
[INFO] Final Memory: 23M/1432M
[INFO] ------------------------------------------------------------------------

```

**Comment by michael-conway** [comment]
testDeleteCollNoForceBug216 is resolved in 4.2.4 and the unit test is activated and run only from 4.2.4 onwards.

testDeleteACollectionWithAmpInTheNameBug170 still persists as an issue, will therefore move this to the pending irods issue and retest in later versions

**Comment by michael-conway** [comment]
@korydraughn  and @trel we can perhaps sometime soon review some of these pending irods issues and add some iRODS issues and tests?
