### ISSUE TITLE
Looking into Java with iRods

### ISSUE THREAD

**Issue by jjkoehorst** [DICE-UNC/jargon#321]
For a project I am currently involved in we are looking into iRods for all its wonderful features. Beside the standard i commands we are also looking into API usages. So far the python API seems relatively straight forward yet I was curious about using the Java API for various implementations either as standalone applications that talk with the iRods interface or as a web interface most likely in combination with Vaadin.

However, I looked into the documentation but it remains fairly vague how to setup the iRods jargon code base. I tried to setup a maven or gradle java basis managed to obtain the dependencies but am unable to perform an authentication with the server. First I thought it was the iRods setup but the python libraries seem to connect nicely.

I have looked into the documentation here: https://github.com/DICE-UNC/jargon/wiki/Authentication
Although its from 2015 I hopefully can assume that the basic interface hasn't changed much? 

An initial setup looks as followed:

```
public class App {

    private static String userName = "rods";
    private static String password = "rods";
    private static String host = "10.XXX.XXX.XXX";
    private static int port = 1247;
    private static String defaultZone = "tempZone";
    private static String home = "/" + defaultZone + "/home/" + userName;
    private static String defaultStorageResource = "demoResc";

    public static void main(String[] args) throws JargonException {
        System.out.println("Starting...");

        IRODSAccount irodsAccount = IRODSAccount.instance(
                host,port,userName,password,home,defaultZone,defaultStorageResource, AuthScheme.STANDARD);

        IRODSFileSystem irodsFileSystem = IRODSFileSystem.instance();

        IRODSAccessObjectFactory accessObjectFactory = irodsFileSystem.getIRODSAccessObjectFactory();

        AuthResponse x = accessObjectFactory.authenticateIRODSAccount(irodsAccount);
        System.out.println(">>" + x.getAuthMessage());

        IRODSFileFactory fileFactory = accessObjectFactory.getIRODSFileFactory(irodsAccount);
```

It however throws an SSL socket issue:

```
Exception in thread "main" org.irods.jargon.core.exception.JargonException: unable to start SSL socket
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocol(SslConnectionUtilities.java:151)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocolAndIntegrateIntoProtocol(SslConnectionUtilities.java:176)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.wrapConnectionInSslIfConfigured(ClientServerNegotiationService.java:193)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.notifyServerOfNegotiationSuccess(ClientServerNegotiationService.java:170)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiateUsingServerProtocol(ClientServerNegotiationService.java:136)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiate(ClientServerNegotiationService.java:107)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiation(AuthMechanism.java:166)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiationHook(AuthMechanism.java:77)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:205)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:223)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:97)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:497)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:399)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:75)
	at App.main(App.java:29)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocol(SslConnectionUtilities.java:148)
	... 16 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	... 20 more

Process finished with exit code 1
```

Is there a location with more in-depth guidelines on starting a project with iRods / Jargon or knows what is happening here?

**Comment by michael-conway** [comment]
PS as a quick test you can set the irods core.re to CS_NEG_REFUSE, or do the same in jargon.properties

ssl.negotiation.policy=CS_NEG_REFUSE


You can manipulate the jargon properties in code as well. This will turn off SSL and you should get through OK. Note that SSL is also required when doing PAM authentication, and you can't do PAM without SSL!

**Comment by jjkoehorst** [comment]
Thanks for the information, I am trying to get a self-signed certificate but I am probably missing a crucial step...

I noticed that in the `/var/lib/irods/.irods/irods_environment.json` file I already have the `"irods_client_server_policy": "CS_NEG_REFUSE",` but of course this is different than the ssl.negotation.policy. 

In core.re I found that `acPreConnect(*OUT) { *OUT="CS_NEG_DONT_CARE"; }` was default? Or is what you mean another variable?

Currently I don't really mind to turn off all kinds of security as this is on a demo server although eventually there will be an irods instance with all the bells and whistles.

**Comment by trel** [comment]
If both sides of the connection are set to `CS_NEG_DONT_CARE`, then the server will try to connect via SSL.

Set either the server or jargon to `CS_NEG_REFUSE`, and the SSL attempt will not occur.

**Comment by jjkoehorst** [comment]
Almost there, I am now able to almost connect with the server. I'll try to dive more into it to see what is going on as it does not seem to find the connection method.

```
            System.out.println("Starting...");

            IRODSAccount irodsAccount = IRODSAccount.instance(
                    host,port,userName,password,home,defaultZone,defaultStorageResource, AuthScheme.STANDARD);

            IRODSFileSystem irodsFileSystem = IRODSFileSystem.instance();

            IRODSAccessObjectFactory accessObjectFactory = irodsFileSystem.getIRODSAccessObjectFactory();

            AuthResponse x = accessObjectFactory.authenticateIRODSAccount(irodsAccount);
            System.out.println(">>" + x.getAuthMessage());

            IRODSFileFactory fileFactory = accessObjectFactory.getIRODSFileFactory(irodsAccount);
```

```
java.lang.NoSuchMethodError: org.irods.jargon.core.connection.IRODSSession.currentConnection(Lorg/irods/jargon/core/connection/IRODSAccount;)Lorg/irods/jargon/core/connection/IRODSMidLevelProtocol;

	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:75)
	at nl.wur.ssb.backend.IRodsTest.testConnection(IRodsTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by michael-conway** [comment]
Not sure what's happening there. what version is this? Are you pulling from maven? That's pretty strange! 

Can we do this..change your ref to 4.3.0.2-SNAPSHOT in Maven.

NB you don't need to explicitly call authenticate, it happens under the covers and you don't really need to add that step.

**Comment by jjkoehorst** [comment]
This might be a silly mistake, with a correct username / password it seems to work but the error still sounds odd. Now looking into if I can list the data and continue with the wiki documentation.

Thanks!

**Comment by jjkoehorst** [comment]
I just performed a close / start of IntelliJ / clean build etc.. and now when using the wrong password it gives as expected

```
org.irods.jargon.core.exception.AuthenticationException
: AuthenticationException
...
```

This is when using `<version>4.3.0.2-SNAPSHOT</version>`

**Comment by michael-conway** [comment]
what was the previous version? That really is exceedingly odd b/c it's well covered in the test suites...

But yes, you can explicitly authenticate for cases where you are doing a login 'form', but otherwise you can just use the factories and it does this under the covers. Check out the jargon unit test classes there's a lot of good usage tips in those test suites. I'm happy to just webex at some point if you want to talk thru some live code or see how some use cases can be addressed.

MC

**Comment by trel** [comment]
Opening issues is generally fine if you think you've found something not working.

Otherwise, the irods-chat list is better for discussing different approaches to solving a problem.  The community is still tight enough that discussion of various tools and clients is still on-topic.

Closing - thanks!
