### ISSUE TITLE
Server connection lost, due to error

### ISSUE THREAD

**Issue by bingzhang** [DICE-UNC/jargon#340]
Hello:

I installed iRODS server from binary on ubuntu 16.04 xenial. I can use icommands without any issue. I try jargon client to connect to my iRODS server. The below code throws Exception:

I check the code, it seems https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/connection/IRODSMidLevelProtocol.java#L1217
returns very large number 0x45000000. 

So should it be 0x45?

`	    IRODSFileFactory irodsFileFactory = irodsAccessObjectFactory.getIRODSFileFactory(irodsAccount);`

```
158  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - send bytes:00000084
159  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - clientServerNegotiationHook()
159  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - negotiation is required
159  [main] DEBUG org.irods.jargon.core.connection.AuthMechanism  - clientServerNegotiation()
159  [main] DEBUG org.irods.jargon.core.connection.IRODSMidLevelProtocol  - reading message from irods
159  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - IRODSConnection.read, byte array size =  4
159  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - offset = 0
159  [main] DEBUG org.irods.jargon.core.connection.AbstractConnection  - length = 4
162  [main] WARN  org.irods.jargon.core.connection.IRODSSession  - discarding irods session for: irods://irods@irodsserver:5432
162  [main] WARN  org.irods.jargon.core.connection.IRODSSession  - discarding session that is already closed, silently ignore
Exception in thread "main" org.irods.jargon.core.exception.JargonException: Server connection lost, due to error
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readHeader(IRODSMidLevelProtocol.java:1240)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:886)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:871)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiation(AuthMechanism.java:123)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiationHook(AuthMechanism.java:72)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:194)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:212)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:95)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394)
	at org.irods.jargon.core.pub.IRODSGenericAO.<init>(IRODSGenericAO.java:61)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImpl.<init>(IRODSFileFactoryImpl.java:42)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.getIRODSFileFactory(IRODSAccessObjectFactoryImpl.java:341)
```

**Comment by michael-conway** [comment]
Sure, remember in Docker-land that 'localhost' refers to the actual docker image itself, not the machine running the docker image. If you do an ifconfig inside of the docker image, you should see an interface which represents the docker bridge network. Using this network address as the source of the client postgres request in the pg_hba.conf would have a similar effect. Running postgres as a docker image is just doing the same thing, but utilizing the container-to-container networking in Docker to resolve this.

Glad you got something up and running! If it's OK I'd like to close this issue. It's a great reference though that can help other people! Thanks, mc

**Comment by bingzhang** [comment]
@michael-conway, I did not use docker to run postgres and irods server. The exception is thrown by the code at https://github.com/DICE-UNC/jargon/blob/master/jargon-core/src/main/java/org/irods/jargon/core/connection/IRODSMidLevelProtocol.java#L1240
Because the length is larger than 10000000. 


Regards,
Bing.

**Comment by bingzhang** [comment]
Can we reopen it, please?

**Comment by michael-conway** [comment]
Sure, sorry I assumed the postgres fix took care of it! Are you trying to go to port 5432? That's a postgres port. I wonder what happens if you use port 1247, which is the default iRODS port? 

If you are indeed going to the wrong port than the error definitely could occur!

**Comment by bingzhang** [comment]
Thanks @michael-conway, after changing to 1247 port. I have another exception "unable to start SSL socket"


24493 [main] DEBUG org.irods.jargon.core.connection.ClientServerNegotiationService  - wrapConnectionInSsl()
24493 [main] DEBUG org.irods.jargon.core.connection.ClientServerNegotiationService  - wrapping in ssl connection
24495 [main] INFO  org.irods.jargon.core.connection.SslConnectionUtilities  - createSslSocketForProtocolAndIntegrateIntoProtocol()
24699 [main] DEBUG org.irods.jargon.core.connection.SslConnectionUtilities  - getting ssl socket factory
24700 [main] DEBUG org.irods.jargon.core.connection.SslConnectionUtilities  - supported cyphers:TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
24713 [main] DEBUG org.irods.jargon.core.connection.SslConnectionUtilities  - ssl socket created for credential exchage..now connect
24714 [main] DEBUG org.irods.jargon.core.connection.SslConnectionUtilities  - supported protocols:SSLv2Hello
24715 [main] DEBUG org.irods.jargon.core.connection.SslConnectionUtilities  - starting SSL handshake
24721 [main] ERROR org.irods.jargon.core.connection.SslConnectionUtilities  - ssl exception in handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocol(SslConnectionUtilities.java:148)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocolAndIntegrateIntoProtocol(SslConnectionUtilities.java:176)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.wrapConnectionInSslIfConfigured(ClientServerNegotiationService.java:192)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.notifyServerOfNegotiationSuccess(ClientServerNegotiationService.java:169)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiateUsingServerProtocol(ClientServerNegotiationService.java:135)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiate(ClientServerNegotiationService.java:106)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiation(AuthMechanism.java:158)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiationHook(AuthMechanism.java:72)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:194)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:212)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:95)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394)
	at org.irods.jargon.core.pub.IRODSGenericAO.<init>(IRODSGenericAO.java:61)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImpl.<init>(IRODSFileFactoryImpl.java:42)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.getIRODSFileFactory(IRODSAccessObjectFactoryImpl.java:341)
	at examples.List.main(List.java:28)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	... 22 more
Exception in thread "main" org.irods.jargon.core.exception.JargonException: unable to start SSL socket
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocol(SslConnectionUtilities.java:151)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocolAndIntegrateIntoProtocol(SslConnectionUtilities.java:176)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.wrapConnectionInSslIfConfigured(ClientServerNegotiationService.java:192)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.notifyServerOfNegotiationSuccess(ClientServerNegotiationService.java:169)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiateUsingServerProtocol(ClientServerNegotiationService.java:135)
	at org.irods.jargon.core.connection.ClientServerNegotiationService.negotiate(ClientServerNegotiationService.java:106)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiation(AuthMechanism.java:158)
	at org.irods.jargon.core.connection.AuthMechanism.clientServerNegotiationHook(AuthMechanism.java:72)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:194)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:212)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:95)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394)
	at org.irods.jargon.core.pub.IRODSGenericAO.<init>(IRODSGenericAO.java:61)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImpl.<init>(IRODSFileFactoryImpl.java:42)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.getIRODSFileFactory(IRODSAccessObjectFactoryImpl.java:341)
	at examples.List.main(List.java:28)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.irods.jargon.core.connection.SslConnectionUtilities.createSslSocketForProtocol(SslConnectionUtilities.java:148)
	... 18 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)

**Comment by bingzhang** [comment]
this is a snippet of my code.


```
	    IRODSAccount irodsAccount = new IRODSAccount(host, port, loginuser, passwd, homedir, zoneName, defaultStorageResc);
	    System.out.println(irodsAccount);
	    
	    IRODSFileSystem irodsFileSystem = IRODSFileSystem.instance();
	    
	    IRODSAccessObjectFactory irodsAccessObjectFactory = irodsFileSystem.getIRODSAccessObjectFactory();
	    
	    IRODSFileFactory irodsFileFactory = irodsAccessObjectFactory.getIRODSFileFactory(irodsAccount);
```

**Comment by michael-conway** [comment]
Good deal, yes, this is likely because you don't have an SSL cert installed
on iRODS. Go into your core.re in /etc/irods and make sure to set the
client server negotiation to CS_NEG_REFUSE from CS_NEG_DONT_CARE and iRODS
won't try to use SSL.

**Comment by bingzhang** [comment]
Thank you very much, @michael-conway!  I changed the negotiation to CS_NEG_REFUSE and restart iRODS server. However, I still get another exception. May I have some help on it, please?

 I noticed "errorEnum val:CAT_INVALID_USER", I used the default username irods and already created that username into postgres db.

```
216  [main] DEBUG org.irods.jargon.core.connection.IRODSErrorScanner  - scanning for info value...
216  [main] DEBUG org.irods.jargon.core.connection.IRODSErrorScanner  - errorEnum val:CAT_INVALID_USER
Exception in thread "main" org.irods.jargon.core.exception.InvalidUserException: InvalidUserException
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:134)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:115)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.processMessageInfoLessThanZero(IRODSMidLevelProtocol.java:1399)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:903)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:871)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:284)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:410)
	at org.irods.jargon.core.connection.StandardIRODSAuth.sendStandardPassword(StandardIRODSAuth.java:54)
	at org.irods.jargon.core.connection.StandardIRODSAuth.processAuthenticationAfterStartup(StandardIRODSAuth.java:124)
	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:196)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:212)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:95)
	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)
	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)
	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487)
	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394)
	at org.irods.jargon.core.pub.IRODSGenericAO.<init>(IRODSGenericAO.java:61)
	at org.irods.jargon.core.pub.io.IRODSFileFactoryImpl.<init>(IRODSFileFactoryImpl.java:42)
	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.getIRODSFileFactory(IRODSAccessObjectFactoryImpl.java:341)
```

**Comment by trel** [comment]
The generic default user within iRODS is usually `rods`, not `irods`.  This connection will be the same as one you could make via iCommands.

**Comment by bingzhang** [comment]
Thank you all. I think I fixed the problem. I have to use iadmin moduser to set the password.
