### ISSUE TITLE
PAM authentication problem

### ISSUE THREAD

**Issue by a-tsygan** [DICE-UNC/jargon#373]
configuration: Docker/Kubernetes
server: TomCat9.
Authentication method: PAM 
Jargon release: 4.3.2
Problem: 
We have an authentication problem. Initial authentication works. We generate token (the code is similar to the REST-API) and then after trying to re-use criterions PAM authentication fails. We are doing IRODSAccount.instance with every request from the token. 
And:
		setIrodsAccessObjectFactory( IRODSAccessObjectFactoryImpl.instance(
											IRODSSession.instance(IRODSSimpleProtocolManager.instance())
										)
								   
									);

All values are not empty, but from time to time we have error with authentication. 
we see or: PAM Authentication error (when token is set already) or failed to fetch PAM temp password 
The only solution that fixes our case is to call: 
IRODSMidLevelProtocol connection_result = this.getIrodsAccessObjectFactory().getIrodsSession().currentConnectionCheckRenewalOfSocket(this.getIRODSAccount());
this heals session and returns correct result, but it makes requests absolutely slow (I think this reset call blocks simultaneous execution of the requests as well).  More over:
when we call authenticateIRODSAccountUtilizingCachedConnectionIfPresent and then check isConnected: it returns true.
and then we get:
org.irods.jargon.core.exception.JargonException: java.io.IOException: read length is set to zero
probably like no connection. 
We do not see this problem when we use STANDARD authentication with the same code

**Comment by a-tsygan** [comment]
some extra information: 
when I call this code: PAM Authentication problem persists for any request:
	    this.l_irodsAccount = IRODSAccount.instance( p_host, p_port, p_username, p_password,
							     p_home, p_defaultZone, p_defaultResc, p_auth);
		// Init other needed objects
		System.out.println("Set connection for: " + getIRODSAccount().getUserName());

		setIrodsAccessObjectFactory( IRODSAccessObjectFactoryImpl.instance(
											IRODSSession.instance(IRODSSimpleProtocolManager.instance())
										)
								   
									);

   	 	SettableJargonProperties jp = new SettableJargonProperties();
   	 	jp.setReconnectTimeInMillis(100000000);
   	 	jp.setPamTimeToLive(100000000);
   	 	jp.setPAMTimeToLive(100000000);
   	 	getIrodsAccessObjectFactory().getIrodsSession().setJargonProperties(jp);
		
	   	authResponse = irodsAccessObjectFactory.authenticateIRODSAccount(this.l_irodsAccount);

**Comment by a-tsygan** [comment]
the stack  traces that we see:
FAILED(e_connectioncheck):org.irods.jargon.core.exception.AuthenticationException: PAM authentication error

org.irods.jargon.core.exception.AuthenticationException: PAM authentication error

	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:187)

	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:115)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.processMessageInfoLessThanZero(IRODSMidLevelProtocol.java:1399)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:903)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:871)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:284)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:410)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:766)

	at org.irods.jargon.core.connection.PAMAuth.processAuthenticationAfterStartup(PAMAuth.java:67)

	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:198)

	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:212)

	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:95)

	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)

	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)

	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487)

	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394)

	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:75)

	at rugirodsrest.RugIRODSConnector.validateConnection2(RugIRODSConnector.java:197)

	at rugirodsrest.RugIRODSConnector.setConnetion(RugIRODSConnector.java:280)

	at rugirodsrest.RugIRODSConnector.setIRODSAccountFromBasicAuthValues(RugIRODSConnector.java:347)

	at rugirodsrest.RugIRODSConnector.<init>(RugIRODSConnector.java:410)

	at rugirodsrest.RugIRODSRestMain.getSessionIRODSConnection(RugIRODSRestMain.java:109)

	at rugirodsrest.RugIRODSRestMain.getObjectDataUsrPriv(RugIRODSRestMain.java:1562)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)

	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)

	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)

	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)

	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)

	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)

	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)

	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)

	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:748)

Renewing connection

IRODS Connector RenewConnection:  can not check current connection (e_connectioncheck)

FAILED(e_connectioncheck):org.irods.jargon.core.exception.AuthenticationException: unable to retrieve the temp password resulting from the pam auth response

org.irods.jargon.core.exception.AuthenticationException: unable to retrieve the temp password resulting from the pam auth response

	at org.irods.jargon.core.connection.PAMAuth.processAuthenticationAfterStartup(PAMAuth.java:88)

	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:198)

	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:212)

	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:95)

	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)

	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)

	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487)

	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394)

	at org.irods.jargon.core.connection.IRODSSession.currentConnectionCheckRenewalOfSocket(IRODSSession.java:441)

	at rugirodsrest.RugIRODSConnector.RenewConnection(RugIRODSConnector.java:135)

	at rugirodsrest.RugIRODSConnector.validateConnection2(RugIRODSConnector.java:202)

	at rugirodsrest.RugIRODSConnector.setConnetion(RugIRODSConnector.java:280)

	at rugirodsrest.RugIRODSConnector.setIRODSAccountFromBasicAuthValues(RugIRODSConnector.java:347)

	at rugirodsrest.RugIRODSConnector.<init>(RugIRODSConnector.java:410)

	at rugirodsrest.RugIRODSRestMain.getSessionIRODSConnection(RugIRODSRestMain.java:109)

	at rugirodsrest.RugIRODSRestMain.getObjectDataUsrPriv(RugIRODSRestMain.java:1562)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)

	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)

	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)

	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)

	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)

	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)

	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)

	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)

	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:748)

isConnected()

AGAIN IRODS reports that we are not connected... validate connection and then check if we are connected LAST TIME

FAILED(e_connectioncheck):org.irods.jargon.core.exception.AuthenticationException: PAM authentication error

validateConnection2()

IRODS Connector can not be initialised (e_c2: setConnetio n- validateConnection2) retry: RenewConnection

FAILED(e_connectioncheck):org.irods.jargon.core.exception.AuthenticationException: unable to retrieve the temp password resulting from the pam auth response

org.irods.jargon.core.exception.AuthenticationException: unable to retrieve the temp password resulting from the pam auth response

	at org.irods.jargon.core.connection.PAMAuth.processAuthenticationAfterStartup(PAMAuth.java:88)

	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:198)

	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:212)

	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:95)

	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)

	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)

	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487)

	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394)

	at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:75)

	at rugirodsrest.RugIRODSConnector.validateConnection2(RugIRODSConnector.java:197)

	at rugirodsrest.RugIRODSConnector.setConnetion(RugIRODSConnector.java:288)

	at rugirodsrest.RugIRODSConnector.setIRODSAccountFromBasicAuthValues(RugIRODSConnector.java:347)

	at rugirodsrest.RugIRODSConnector.<init>(RugIRODSConnector.java:410)

	at rugirodsrest.RugIRODSRestMain.getSessionIRODSConnection(RugIRODSRestMain.java:109)

	at rugirodsrest.RugIRODSRestMain.getObjectDataUsrPriv(RugIRODSRestMain.java:1562)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)

	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)

	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)

	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)

	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)

	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)

	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)

	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)

	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:748)

Renewing connection

IRODS Connector RenewConnection:  can not check current connection (e_connectioncheck)

FAILED(e_connectioncheck):org.irods.jargon.core.exception.AuthenticationException: PAM authentication error

org.irods.jargon.core.exception.AuthenticationException: PAM authentication error

	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:187)

	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:115)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.processMessageInfoLessThanZero(IRODSMidLevelProtocol.java:1399)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:903)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:871)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:284)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:410)

	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:766)

	at org.irods.jargon.core.connection.PAMAuth.processAuthenticationAfterStartup(PAMAuth.java:67)

	at org.irods.jargon.core.connection.AuthMechanism.authenticate(AuthMechanism.java:198)

	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.authenticate(AbstractIRODSMidLevelProtocolFactory.java:212)

	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:95)

	at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:139)

	at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:56)

	at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:487)

	at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:394)

	at org.irods.jargon.core.connection.IRODSSession.currentConnectionCheckRenewalOfSocket(IRODSSession.java:441)

	at rugirodsrest.RugIRODSConnector.RenewConnection(RugIRODSConnector.java:135)

	at rugirodsrest.RugIRODSConnector.validateConnection2(RugIRODSConnector.java:202)

	at rugirodsrest.RugIRODSConnector.setConnetion(RugIRODSConnector.java:288)

	at rugirodsrest.RugIRODSConnector.setIRODSAccountFromBasicAuthValues(RugIRODSConnector.java:347)

	at rugirodsrest.RugIRODSConnector.<init>(RugIRODSConnector.java:410)

	at rugirodsrest.RugIRODSRestMain.getSessionIRODSConnection(RugIRODSRestMain.java:109)

	at rugirodsrest.RugIRODSRestMain.getObjectDataUsrPriv(RugIRODSRestMain.java:1562)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)

	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)

	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)

	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)

	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)

	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)

	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)

	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)

	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)

	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)

	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)

	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)

	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)

	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)

	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)

	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)

	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)

	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)

	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)

	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)

	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

	at java.lang.Thread.run(Thread.java:748)

**Comment by michael-conway** [comment]
Hi it looks like this might be a REST service via Jersey? I think otherwise I'd look at how you are getting the connections, and I'd highly recommend using a Filter pattern and a connection per request model?

I'll look for an example but I think changing the usage a bit will clear this up...

**Comment by michael-conway** [comment]
Just checking back, but there are two important things that can help you solve the issue, first is just on usage, and there's a little guide that can perhaps help you in configuring the infrastructure for connecting (there are also some nice ways to use Spring dependency injection with these pieces) - https://github.com/DICE-UNC/jargon/blob/master/user-guide/connecting.md

Second, it's highly recommended that you use a session-per-request pattern and implement your connection managment in a servlet filter arrangement. 

The connections in jargon are handled by a ThreadLocal cache, and when you use IRODSAccessObjectFactory to get a service object, it simply reuses the conn in the ThreadLocal pool. In this way, you can just auth, the connection will remain open from the auth process or will be opened on the first access (so when you say irodsAccessObjectFactory.getXXXAO() it will either connect or pull the current connection out of the ThreadLocal when you talk to iRODS, you don't need to do anything within your code to manage the connections. The key is to call one of the irodsAccessObjectFactory.closeXXX() methods. You can either close all conns, or close only the conn associated with the irodsAccount (you can open conns to multiple hosts at the same time). Doing this in the servlet filter post request processing is highly recommended and removes any conn handling code from any of your REST services.

NB there is some plumbing to use a connection pool or cache underneath, that's a different subject. Since the conns are segregated by ThreadLocal you should have no concerns about multithreaded access, it works very will in service type scenarios.

See if these points help you otherwise let me know!

**Comment by michael-conway** [comment]
PS I will close this just for organizing but if you find issues (I don't think you will once you adjust the conn creating code) feel free to reoopen! You can also contact me at michael.c.conway@gmail.com if you want to chat about this. Happy New Year!
