### ISSUE TITLE
File rename/phy move to a different resource fails in 4.2.9 with missing leaf resource or replica number

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#374]
a rename that is a phy move to another resource seems to hit changes in 4.2.9..

"error code received from iRODS:-316000 message:Source hierarchy or leaf resource or replica number required - none provided"

This is a new behavior. Will @Ignore in the test and fix under this issue

```Java

/**
	 * Test method for
	 * {@link org.irods.jargon.core.pub.io.IRODSFileImpl#renameTo(java.io.File)} .
	 */
	@Test
	public final void testRenameToFileFilePhyMove() throws Exception {
		String testFileName = "testRenameFileToFilePhyMove.txt";

		String absPath = scratchFileUtils.createAndReturnAbsoluteScratchPath(IRODS_TEST_SUBDIR_PATH);
		FileGenerator.generateFileOfFixedLengthGivenName(absPath, testFileName, 8);

		String targetIrodsCollection = testingPropertiesHelper
				.buildIRODSCollectionAbsolutePathFromTestProperties(testingProperties, IRODS_TEST_SUBDIR_PATH);

		StringBuilder fileNameAndPath = new StringBuilder();
		fileNameAndPath.append(absPath);

		fileNameAndPath.append(testFileName);

		IRODSAccount irodsAccount = testingPropertiesHelper.buildIRODSAccountFromTestProperties(testingProperties);

		IRODSAccessObjectFactory accessObjectFactory = irodsFileSystem.getIRODSAccessObjectFactory();

		DataTransferOperations dto = accessObjectFactory.getDataTransferOperations(irodsAccount);
		dto.putOperation(fileNameAndPath.toString(), targetIrodsCollection,
				testingProperties.getProperty(TestingPropertiesHelper.IRODS_RESOURCE_KEY), null, null);

		IRODSFileFactory irodsFileFactory = accessObjectFactory.getIRODSFileFactory(irodsAccount);

		IRODSFile irodsFile = irodsFileFactory.instanceIRODSFile(targetIrodsCollection + '/' + testFileName);
		IRODSFile irodsRenameFile = irodsFileFactory.instanceIRODSFile(targetIrodsCollection + '/' + testFileName);
		irodsRenameFile
				.setResource(testingProperties.getProperty(TestingPropertiesHelper.IRODS_SECONDARY_RESOURCE_KEY));

		irodsFile.renameTo((File) irodsRenameFile);

		DataObjectAO dataObjectAO = accessObjectFactory.getDataObjectAO(irodsAccount);

		DataObject dataObject = dataObjectAO.findByAbsolutePath(targetIrodsCollection + '/' + testFileName);

		Assert.assertEquals("file is not in new resource",
				testingProperties.getProperty(TestingPropertiesHelper.IRODS_SECONDARY_RESOURCE_KEY),
				dataObject.getResourceName());
	}

```

here's the trace

```
org.irods.jargon.core.exception.JargonRuntimeException: org.irods.jargon.core.exception.JargonException: error code received from iRODS:-316000 message:Source hierarchy or leaf resource or replica number required - none provided.
	at org.irods.jargon.core.pub.io.IRODSFileImpl.renameTo(IRODSFileImpl.java:997)
	at org.irods.jargon.core.pub.io.IRODSFileImpl.renameTo(IRODSFileImpl.java:1015)
	at org.irods.jargon.core.pub.io.IRODSFileImplTest.testRenameToFileFilePhyMove(IRODSFileImplTest.java:1861)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.irods.jargon.core.exception.JargonException: error code received from iRODS:-316000 message:Source hierarchy or leaf resource or replica number required - none provided.
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:282)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:115)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.processMessageInfoLessThanZero(IRODSMidLevelProtocol.java:1542)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:1046)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:1014)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:427)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:553)
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.physicalMove(IRODSFileSystemAOImpl.java:1315)
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.physicalMove(IRODSFileSystemAOImpl.java:1281)
	at org.irods.jargon.core.pub.io.IRODSFileImpl.renameTo(IRODSFileImpl.java:993)
	... 30 more


```

**Comment by trel** [comment]
ping @alanking

**Comment by alanking** [comment]
This aligns with our effort to make `iphymv` (and underlying machinery) much more specific about what you want it to do. In the past, a resource would be chosen and its hierarchy resolved, but we felt that this doesn't make sense in the context of a phymv. The justification for this is that phymv is directly touching replicas, moving from one specific resource to another specific resource, so we now require higher specificity. Unfortunately, I can't seem to find a specific issue which describes this new behavior, but that is why this error message has come about.

To avoid this, you must specify a fully resolved resource hierarchy via `RESC_HIER_STR_KW` and `DEST_RESC_HIER_STR_KW` for source and destination replica, respectively; or, you must specify a leaf resource via `RESC_NAME_KW` and `DEST_RESC_NAME_KW` for source and destination replica, respectively.

We'd be happy to discuss this change further if it seems like it is inappropriate for this point release.
