### ISSUE TITLE
Ticket failures (put data as anonymous with valid ticket) fails in 4-2+

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#376]
Stack trace from unit test 
```
org.irods.jargon.core.exception.DataNotFoundException: No data found
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:138)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:115)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.processMessageInfoLessThanZero(IRODSMidLevelProtocol.java:1542)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:1046)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:1014)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunctionIncludingAllDataInStream(IRODSMidLevelProtocol.java:725)
	at org.irods.jargon.core.pub.DataAOHelper.processNormalPutTransfer(DataAOHelper.java:456)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putCommonProcessing(DataObjectAOImpl.java:587)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putLocalDataObjectToIRODS(DataObjectAOImpl.java:395)
	at org.irods.jargon.core.pub.TransferOperationsHelper.processPutOfSingleFile(TransferOperationsHelper.java:822)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.processPutAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:793)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:673)
	at org.irods.jargon.ticket.TicketClientOperationsImpl.putFileToIRODSUsingTicket(TicketClientOperationsImpl.java:89)
	at org.irods.jargon.ticket.TicketClientOperationsImpl.redeemTicketAndStreamToIRODSCollection(TicketClientOperationsImpl.java:194)
	at org.irods.jargon.ticket.TicketClientOperationsImplTest.testRedeemTicketAndStreamToIRODSCollectionAsAnonymous(TicketClientOperationsImplTest.java:1060)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)


```

For unit test in jargon-ticket

https://github.com/DICE-UNC/jargon/blob/master/jargon-ticket/src/test/java/org/irods/jargon/ticket/TicketClientOperationsImplTest.java#L1004-L1069

**Comment by trel** [comment]
@d-w-moore is this possibly related to our recent ticket learnings?

**Comment by d-w-moore** [comment]
> @d-w-moore is this possibly related to our recent ticket learnings?

I'd guess not.  https://github.com/irods/irods/issues/7250 is all about multiple simultaneous connections, and I didn't see any of these happening in the Java tests.  

Of course, client connections appear to be implicit in code using the Jargon library, so I guess there could be any number of them working under the surface of these fairly high level abstractions: `ShoppingCartService`, `DataCacheServiceFactory`, etc

**Comment by michael-conway** [comment]
I can chat some time on this but connections are segregated by thread. This
way you can't have agents misbehave on mixed operations.

Conns are kept in a Thread local and therefore you don't need to pass them
around as shared refs in message calls etc. It was based on the Hibernate
libraries

**Comment by d-w-moore** [comment]
> I can chat some time on this but connections are segregated by thread. This way you can't have agents misbehave on mixed operations. Conns are kept in a Thread local and therefore you don't need to pass them around as shared refs in message calls etc. It was based on the Hibernate libraries

Sounds smart.  

Where I ran into trouble with tickets recently, that is https://github.com/irods/irods/issues/7250 -- and this was a hard-to-prove bug and required that a particular ticket be activated on two connections at the same time -- was that if we made certain calls on one of those connections, the same call would lock on the other connection.  The first conn was trying to update ticket statistics but not giving up the handle to the DB ("committing") and the second would come along and find itself locked out.

**Comment by d-w-moore** [comment]
> That said, I don't know if PRC has a test around put-as-anonymous with tickets active.

Looking into it, PRC test suite does a data open for write using the anonymous user in `irods.test,ticket.test.TestTicketOps.test_data_ticket_write`, but I don't know if this would be equivalent to a Jargon PUT.
