### ISSUE TITLE
Transfer of 100gb+ to local environment

### ISSUE THREAD

**Issue by jjkoehorst** [DICE-UNC/jargon#410]
I am using a local java application to transfer files from and to irods. This works fine for relatively small files <20gb but when I was transferring a bigger file it seems to just "hang" still trying to find out what happens. 

To investigate this further I was planning to implement a transfer listener so it can report how much has been transferred so far.
However how to implement this function is currently unclear to me.

I initiated a default transfer control block which has a `getTotalBytesTransferredSoFar()` but this might only work when transferring multiple files and report in the end?

In addition it now also reports other transfer errors which were hidden before. Any clue what I am missing here?

I will probably move the TransferControlBlock to a more general location thus when transferring multiple files I only have one instance.

```
        if (!localFile.exists()) {
            logger.info("Downloading file from " + irodsFile + " to " + localFile.getAbsolutePath());
            try {
                TransferControlBlock transferControlBlock = DefaultTransferControlBlock.instance();
                dataTransferOperationsAO.getOperation(irodsFile, localFile, null, transferControlBlock);
            } catch (JargonException e) {
                if (localFile.exists()) {
                    localFile.delete();
                }
                throw new JargonException("Download failed");
            }
```

```
08:39:17.105 [pool-2-thread-3] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread - unchecked exception in transfer
java.net.SocketException: No buffer space available
        at sun.nio.ch.Net.setIntOption0(Native Method) ~[?:?]
        at sun.nio.ch.Net.setSocketOption(Net.java:455) ~[?:?]
        at sun.nio.ch.Net.setSocketOption(Net.java:393) ~[?:?]
        at sun.nio.ch.NioSocketImpl.setOption(NioSocketImpl.java:1049) ~[?:?]
        at java.net.DelegatingSocketImpl.setOption(DelegatingSocketImpl.java:154) ~[?:?]
        at java.net.Socket.setSendBufferSize(Socket.java:1278) ~[?:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:87) [IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:32) [IRODSTransfer.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
08:41:17.132 [pool-2-thread-4] ERROR org.irods.jargon.core.transfer.AbstractParallelTransferThread - IOExeption in parallel transfer
java.net.SocketTimeoutException: Read timed out
        at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
        at java.io.FilterInputStream.read(FilterInputStream.java:106) ~[?:?]
        at org.irods.jargon.core.transfer.AbstractParallelTransferThread.readInt(AbstractParallelTransferThread.java:46) [IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:210) [IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:179) [IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:147) [IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:32) [IRODSTransfer.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
08:41:17.145 [pool-2-thread-4] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread - a jargon exception occurred in the get loop
08:41:17.221 [pool-2-thread-4] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread - unchecked exception in transfer
org.irods.jargon.core.exception.JargonException: IOException occurred during parallel file transfer
        at org.irods.jargon.core.transfer.AbstractParallelTransferThread.readInt(AbstractParallelTransferThread.java:49) ~[IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:210) ~[IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:179) ~[IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:147) [IRODSTransfer.jar:?]
        at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:32) [IRODSTransfer.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.net.SocketTimeoutException: Read timed out
        at sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283) ~[?:?]
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:?]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
        at java.io.FilterInputStream.read(FilterInputStream.java:106) ~[?:?]
        at org.irods.jargon.core.transfer.AbstractParallelTransferThread.readInt(AbstractParallelTransferThread.java:46) ~[IRODSTransfer.jar:?]
        ... 8 more
```

**Comment by jjkoehorst** [comment]
Manage to solve the transfer listener at https://git.wur.nl/unlock/irodstransfer
