### ISSUE TITLE
(Yoda) .canWrite() - jargon exception, rethrow as unchecked - Exception processing specific query

### ISSUE THREAD

**Issue by jjkoehorst** [DICE-UNC/jargon#422]
Hello,

I am connecting to a Yoda instance which has hacked around in iRODS making it so that not all functionalities are available (don't ask me why). Unfortunately canWrite() is one of them and when I check if a user has write permissions it throws a (see below)...

Which in principle is ok but is there a way to catch this error? I was trying a simple:

                try {
                    writable = credentials.getFileFactory().instanceIRODSFile(pathBar.getValue()).canWrite();
                } catch (JargonException e) {
                    // Check if directory is writable, YODA does not have the canWrite() function so on exception return true
                    writable = true;
                    logger.debug("Can write function not available");
                }

But I guess the stack trace is internally to prevent entire breakdown of a process but is there a way to check if a canWrite is possible and handle it accordingly?

```
2023-03-25 08:28:36 [http-nio-8083-exec-4] ERROR o.i.jargon.core.pub.io.IRODSFileImpl - jargon exception, rethrow as unchecked
org.irods.jargon.core.exception.SpecificQueryException: Exception processing specific query
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:173)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:112)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.processMessageInfoLessThanZero(IRODSMidLevelProtocol.java:1606)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:1110)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.readMessage(IRODSMidLevelProtocol.java:1078)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:445)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:571)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:927)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.queryOnAliasGivenDefinition(SpecificQueryAOImpl.java:483)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.executeSpecificQueryUsingAliasWithoutAliasLookup(SpecificQueryAOImpl.java:392)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.findSpecificQueryByAlias(SpecificQueryAOImpl.java:155)
	at org.irods.jargon.core.pub.SpecificQueryAOImpl.executeSpecificQueryUsingAlias(SpecificQueryAOImpl.java:441)
	at org.irods.jargon.core.pub.CollectionAOImpl.findPermissionForUserGrantedThroughUserGroup(CollectionAOImpl.java:1802)
	at org.irods.jargon.core.pub.CollectionAOImpl.getPermissionViaSpecQueryAsGroupMember(CollectionAOImpl.java:1760)
	at org.irods.jargon.core.pub.CollectionAOImpl.getPermissionForUserName(CollectionAOImpl.java:1746)
	at org.irods.jargon.core.pub.CollectionAOImpl.getPermissionForCollection(CollectionAOImpl.java:1661)
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.getDirectoryPermissionsForGivenUser(IRODSFileSystemAOImpl.java:322)
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.getDirectoryPermissions(IRODSFileSystemAOImpl.java:294)
	at org.irods.jargon.core.pub.IRODSFileSystemAOImpl.isFileWriteable(IRODSFileSystemAOImpl.java:224)
	at org.irods.jargon.core.pub.io.IRODSFileImpl.canWrite(IRODSFileImpl.java:337)
	at nl.fairbydesign.views.browser.BrowserView.lambda$new$7a59a3a5$1(BrowserView.java:404)
```

**Comment by korydraughn** [comment]
Perhaps the exception is caused due to the target specific query missing.

Are you still able to produce this?
What version of Jargon are you using?
What version of iRODS are you communicating with?
Have you checked the log file of the iRODS server to see which specific query is being called by Jargon?

**Comment by trel** [comment]
I see this codeblock...

https://github.com/DICE-UNC/jargon/blob/ec1a053c13847dca781bbf8a074d785e0eb53227/jargon-core/src/main/java/org/irods/jargon/core/pub/CollectionAOImpl.java#L1772-L1796

Which is looking for a SpecificQuery by alias `listUserACLForCollectionViaGroup`
That SpecificQuery was added to the catalog in iRODS 3.3.1 in 2013.

Blame shows the Jargon code hasn't moved in 11 years.

So my guess is that you're just missing that SpecificQuery...

https://github.com/irods/irods/blob/ecaf66d06478bbe2a3e7be47d98f04ed97b94e9a/scripts/irods/database_upgrade.py#L24

**Comment by korydraughn** [comment]
Nice find.

**Comment by korydraughn** [comment]
I'm not able to reproduce this against iRODS 4.3.3.

Closing. Please open a new issue if this is still a problem.
