### ISSUE TITLE
irods account with home path may cause URI formatting errors

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#48]
create an iRODS account with a home dir, and then do a toURI on the iRODS account

```Shell


Caused by: org.irods.jargon.core.exception.JargonException: cannot convert this account into a URI:irods://test1@testdfc1.renci.org:1247
        at org.irods.jargon.core.connection.IRODSAccount.toURI(IRODSAccount.java:400)
        at org.irods.jargon.core.connection.AbstractConnection.initializeConnection(AbstractConnection.java:136)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.connection.AbstractConnection.<init>(AbstractConnection.java:106)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.connection.IRODSBasicTCPConnection.<init>(IRODSBasicTCPConnection.java:52)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.connection.IRODSTCPConnectionFactoryImpl.instance(IRODSTCPConnectionFactoryImpl.java:35)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocolFactory.instance(AbstractIRODSMidLevelProtocolFactory.java:93)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.connection.IRODSProtocolManager.createNewProtocol(IRODSProtocolManager.java:175)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.connection.IRODSSimpleProtocolManager.getIRODSProtocol(IRODSSimpleProtocolManager.java:69)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.connection.IRODSSession.connectAndAddToProtocolsMap(IRODSSession.java:340)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.connection.IRODSSession.currentConnection(IRODSSession.java:298)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        at org.irods.jargon.core.pub.IRODSAccessObjectFactoryImpl.authenticateIRODSAccount(IRODSAccessObjectFactoryImpl.java:80)
        at edu.drexel.aig.formatregindex.FileIdentificationIndexer.<init>(FileIdentificationIndexer.java:54)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)[:1.7.0_65]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)[:1.7.0_65]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[:1.7.0_65]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)[:1.7.0_65]
        at org.apache.aries.blueprint.utils.ReflectionUtils.newInstance(ReflectionUtils.java:329)[7:org.apache.aries.blueprint.core:1.4.0]
        at org.apache.aries.blueprint.container.BeanRecipe.newInstance(BeanRecipe.java:962)[7:org.apache.aries.blueprint.core:1.4.0]
        at org.apache.aries.blueprint.container.BeanRecipe.getInstance(BeanRecipe.java:331)[7:org.apache.aries.blueprint.core:1.4.0]
        ... 29 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 58: irods://test1.dfc1@testdfc1.renci.org:1247/dfc1/home/test1 
        at java.net.URI$Parser.fail(URI.java:2829)[:1.7.0_65]
        at java.net.URI$Parser.checkChars(URI.java:3002)[:1.7.0_65]
        at java.net.URI$Parser.parseHierarchical(URI.java:3086)[:1.7.0_65]
        at java.net.URI$Parser.parse(URI.java:3034)[:1.7.0_65]
        at java.net.URI.<init>(URI.java:595)[:1.7.0_65]
        at org.irods.jargon.core.connection.IRODSAccount.toURI(IRODSAccount.java:395)[193:edu.drexel.aig.format-registry-irods-indexer:1.0.0.SNAPSHOT]
        ... 47 more
2014-09-26 17:33:37,380 | INFO  | mix-5.0.1/deploy | fileinstall                      | ?                                   ? | 6 - org.apache.felix.fileinstall - 3.2.8 | Started bundle: file:/var/lib/irods/indexing/indexing/apache-servicemix-5.0.1/deploy/format-registry-irods-indexer-1.0-SNAPSHOT.jar
2014-09-26 17:33:56,885 | INFO  | NioProcessor-2   | ServerSession                    | ?                                   ? | 26 - org.apache.sshd.core - 0.8.0 | Session created from /127.0.0.1:55779
2014-09-26 17:33:57,036 | INFO  | NioProcessor-2   | ServerSession                    | ?                                   ? | 26 - org.apache.sshd.core - 0.8.0 | Session karaf@/127.0.0.1:55779 authenticated






```

**Comment by michael-conway** [comment]
added test (passes)

```java

/**
	 * Tests bug https://github.com/DICE-UNC/jargon/issues/48 irods account with
	 * home path may cause URI formatting errors #48
	 * 
	 * @throws Exception
	 */
	@Test
	public final void testToUriWithHomePathBug48() throws Exception {
		final IRODSAccount account = IRODSAccount.instance("localhost", 1247,
				"client", "password", "/zone/home/client", "zone", "");
		account.toURI(true);
	}


```
