### ISSUE TITLE
Parallel file transfer performance

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#72]
Investigate perceived slowness in parallel file transfer as well as connection timeouts on main thread as observed at iPlant

```

ransferHost:
   transferZone:
2015-02-16 21:23:17,873 19210033 [AWT-EventQueue-0] INFO  org.irods.jargon.idrop.desktop.systraygui.iDrop  - pct done:99
2015-02-16 21:23:18,246 19210406 [pool-5-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  -    operation:9999
2015-02-16 21:23:18,246 19210406 [pool-5-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - done received
2015-02-16 21:23:18,246 19210406 [pool-5-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - closing sockets, this eats any exceptions
2015-02-16 21:23:18,247 19210407 [pool-5-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - socket conns for parallel transfer closed, now close the file stream
2015-02-16 21:23:18,247 19210407 [pool-5-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - streams and files closed
2015-02-16 21:23:23,353 19215513 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - final flush of output buffer
2015-02-16 21:23:23,353 19215513 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - for thread, total read: 24641536
2015-02-16 21:23:23,353 19215513 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  -    total written: 24641536
2015-02-16 21:23:23,353 19215513 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  -    transferLength: 0
2015-02-16 21:23:24,845 19217005 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  -    operation:9999
2015-02-16 21:23:24,845 19217005 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - done received
2015-02-16 21:23:24,845 19217005 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - closing sockets, this eats any exceptions
2015-02-16 21:23:24,845 19217005 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - socket conns for parallel transfer closed, now close the file stream
2015-02-16 21:23:24,845 19217005 [pool-5-thread-4] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - streams and files closed
2015-02-16 21:23:27,031 19219191 [pool-5-thread-3] INFO  org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable  - status callback:transfer status:
   transferState:IN_PROGRESS_START_FILE
   transferType:PUT
   sourceFileAbsolutePath:
   targetFileAbsolutePath:
   targetResource:
   totalSize:2111832064
   bytesTransferred:2110324736
   totalFilesTransferredSoFar:0
   totalFilesSkippedSoFar:0
   totalFilesToTransfer:0
   transferException:null
   intraFileStatusReporttrue
   transferHost:
   transferZone:
2015-02-16 21:23:27,031 19219191 [pool-5-thread-3] INFO  org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable  - file initiation, this is just passed on by conveyor
2015-02-16 21:23:27,031 19219191 [pool-5-thread-3] INFO  org.irods.jargon.idrop.desktop.systraygui.iDrop  - transfer status callback to iDROP:transfer status:
   transferState:IN_PROGRESS_START_FILE
   transferType:PUT
   sourceFileAbsolutePath:
   targetFileAbsolutePath:
   targetResource:
   totalSize:2111832064
   bytesTransferred:2110324736
   totalFilesTransferredSoFar:0
   totalFilesSkippedSoFar:0
   totalFilesToTransfer:0
   transferException:null
   intraFileStatusReporttrue
   transferHost:
   transferZone:
2015-02-16 21:23:27,032 19219192 [AWT-EventQueue-0] INFO  org.irods.jargon.idrop.desktop.systraygui.iDrop  - pct done:99
2015-02-16 21:23:33,825 19225985 [pool-5-thread-3] INFO  org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable  - status callback:transfer status:
   transferState:IN_PROGRESS_START_FILE
   transferType:PUT
   sourceFileAbsolutePath:
   targetFileAbsolutePath:
   targetResource:
   totalSize:2111832064
   bytesTransferred:2111176704
   totalFilesTransferredSoFar:0
   totalFilesSkippedSoFar:0
   totalFilesToTransfer:0
   transferException:null
   intraFileStatusReporttrue
   transferHost:
   transferZone:
2015-02-16 21:23:33,826 19225986 [pool-5-thread-3] INFO  org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable  - file initiation, this is just passed on by conveyor
2015-02-16 21:23:33,826 19225986 [pool-5-thread-3] INFO  org.irods.jargon.idrop.desktop.systraygui.iDrop  - transfer status callback to iDROP:transfer status:
   transferState:IN_PROGRESS_START_FILE
   transferType:PUT
   sourceFileAbsolutePath:
   targetFileAbsolutePath:
   targetResource:
   totalSize:2111832064
   bytesTransferred:2111176704
   totalFilesTransferredSoFar:0
   totalFilesSkippedSoFar:0
   totalFilesToTransfer:0
   transferException:null
   intraFileStatusReporttrue
   transferHost:
   transferZone:
2015-02-16 21:23:33,826 19225986 [AWT-EventQueue-0] INFO  org.irods.jargon.idrop.desktop.systraygui.iDrop  - pct done:99
2015-02-16 21:23:39,146 19231306 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - final flush of output buffer
2015-02-16 21:23:39,146 19231306 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - for thread, total read: 24641536
2015-02-16 21:23:39,147 19231307 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  -    total written: 24641536
2015-02-16 21:23:39,147 19231307 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  -    transferLength: 0
2015-02-16 21:23:41,212 19233372 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  -    operation:9999
2015-02-16 21:23:41,212 19233372 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - done received
2015-02-16 21:23:41,212 19233372 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - closing sockets, this eats any exceptions
2015-02-16 21:23:41,212 19233372 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - socket conns for parallel transfer closed, now close the file stream
2015-02-16 21:23:41,213 19233373 [pool-5-thread-3] INFO  org.irods.jargon.core.transfer.ParallelPutTransferThread  - streams and files closed
2015-02-16 21:23:41,213 19233373 [pool-1-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutFileTransferStrategy  - transfer state:java.util.concurrent.FutureTask@640211b8
2015-02-16 21:23:41,213 19233373 [pool-1-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutFileTransferStrategy  - transfer state:java.util.concurrent.FutureTask@779edb2f
2015-02-16 21:23:41,213 19233373 [pool-1-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutFileTransferStrategy  - transfer state:java.util.concurrent.FutureTask@2b325a07
2015-02-16 21:23:41,213 19233373 [pool-1-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutFileTransferStrategy  - transfer state:java.util.concurrent.FutureTask@304b1f4
2015-02-16 21:23:41,213 19233373 [pool-1-thread-1] INFO  org.irods.jargon.core.transfer.ParallelPutFileTransferStrategy  - executor completed
2015-02-16 21:23:41,213 19233373 [pool-1-thread-1] INFO  org.irods.jargon.core.pub.DataObjectAOImpl  - transfer process is complete
2015-02-16 21:23:41,213 19233373 [pool-1-thread-1] INFO  org.irods.jargon.core.pub.DataObjectAOImpl  - sending operation complete at termination of parallel transfer
2015-02-16 21:24:00,119 19252279 [pool-1-thread-1] ERROR org.irods.jargon.core.connection.AbstractConnection  - exception reading from socket
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:150)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at org.irods.jargon.core.connection.AbstractConnection.read(AbstractConnection.java:624)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readHeaderLength(AbstractIRODSMidLevelProtocol.java:1026)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readHeader(AbstractIRODSMidLevelProtocol.java:912)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:604)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:587)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:228)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:129)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.operationComplete(AbstractIRODSMidLevelProtocol.java:771)
	at org.irods.jargon.core.pub.DataObjectAOImpl.parallelPutTransfer(DataObjectAOImpl.java:868)
	at org.irods.jargon.core.pub.DataObjectAOImpl.processAsAParallelPutOperationIfMoreThanZeroThreads(DataObjectAOImpl.java:776)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putCommonProcessing(DataObjectAOImpl.java:659)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putLocalDataObjectToIRODSCommonProcessing(DataObjectAOImpl.java:552)
	at org.irods.jargon.core.pub.DataObjectAOImpl.putLocalDataObjectToIRODS(DataObjectAOImpl.java:400)
	at org.irods.jargon.core.pub.TransferOperationsHelper.processPutOfSingleFile(TransferOperationsHelper.java:867)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.processPutAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:1015)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:854)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.putOperation(DataTransferOperationsImpl.java:1117)
	at org.irods.jargon.conveyor.core.callables.PutConveyorCallable.processCallForThisTransfer(PutConveyorCallable.java:48)
	at org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable.call(AbstractConveyorCallable.java:208)
	at org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable.call(AbstractConveyorCallable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by michael-conway** [comment]
updates from yesterday as passed to consortium folks



If interested, here's what I'm finding.

1) I keep hitting a situation where the transfer takes a long time (huge file) and the parallel threads seem to complete, but when it goes to send opr complete the main 1247 socket has timed out. I have my client side time-out set to zero.  Does that sound like iRODS or probably some intermediate network location?  I think iRODS has that connection restart thing -T and I had that in jargon at one point but I was unconvinced it was helpful.

Should I revisit -T or treat implementing long file restart as the cleanest approach?


2) In my benchmarking yesterday, I was manipulating the size of the buffer I use when doing the stream2stream copy between fileinputstream and the iRODS parallel transfer output stream.  I also manipulated the thread count, which Jargon has always had with a 4 threads default.

I ended up settling with a combination of a 520K copy buffer and 8 threads.  Outside of that the returns for more threads or larger buffers were not there.

3) I started playing with the 'seek' in the parallel transfer algorithm as being an issue.  jargon had been doing that by just opening a stream and reading up to the seek point, which is, IIRC, always been an i/o trick, but I did try RandomAccessFile and the os level seek() and didn't see any big gain there, and maybe a slight loss.

4) Today I was going to revisit using java NIO File Channels, which has been an 'experimental' option in Jargon for some time.  I did this a couple of years ago and at the time was not overly impressed with any benefits to NIO over normal Java I/O, but that was also several OS and JVM iterations back.  I think it's worth doing again per this:


For the best Java read performance, there are four things to remember:

Minimize I/O operations by reading an array at a time, not a byte at a time. An 8Kbyte array is a good size.
Minimize method calls by getting data an array at a time, not a byte at a time. Use array indexing to get at bytes in the array.
Minimize thread synchronization locks if you don't need thread safety. Either make fewer method calls to a thread-safe class, or use a non-thread-safe class like FileChannel and MappedByteBuffer.
Minimize data copying between the JVM/OS, internal buffers, and application arrays. Use FileChannel with memory mapping, or a direct or wrapped array ByteBuffer.




FWIW I've been testing against the iplant 'ipctest' server from home to get as much networking between my tests and a target server.  I do see the time-outs. I am also right now testing with an iput and honestly, it's no faster, so I remain somewhat skeptical that it's a Java-only issue.

More precise benchmarks that can compare the icommands and the Jargon are in order.

**Comment by michael-conway** [comment]
nb iPut failed with same situation

```
From server: NumThreads=16, addr:128.196.172.248, port:20171, cookie=6130506
==ERROR: readMsgHeader:header read- read 0 bytes, expect 4, status = -4060
ERROR: readAndProcApiReply: readMsgHeader error. status = -4060 status = -4060 SYS_HEADER_READ_LEN_ERR, Operation timed out
ERROR: putUtil: put error for /iplant/home/ipctest/mc_icommand/test600M.dat, status = -4060 status = -4060 SYS_HEADER_READ_LEN_ERR, Operation timed out
Client Caught broken pipe signal. Connection to server may be down
ERROR: writeMsgHeader: wrote 0 bytes for myLen , expect 4, status = -5032
Mike-Conways-MacBook-Pro:temp mikeconway$ ==

```

**Comment by michael-conway** [comment]
add back reconnect reverting from this set of changes..

https://github.com/DICE-UNC/jargon/commit/be71e65d230bf7e2152f7d33de973e271d1ee0ca

**Comment by michael-conway** [comment]
added code to manipulate window sizes on main and parallel put

**Comment by michael-conway** [comment]
add to jargon props and processing...

send receive window sizes
keep alive

**Comment by michael-conway** [comment]
Closing for this wave of changes, will reopen individual detail tickets to break this out, as there are more than one thing at play!
