### ISSUE TITLE
Hang or timeout on get of large collection with large files

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/jargon#81]
per Jerry

 Regression run is holding with previous runs, still missing a lot of names, tooltips and titles.

Tried doing a 37GB (25 file) download from our production server.  Got about 3/4 of way through and then it just hung on an 875K file.  Here is the error reported in the transfer details:
```
org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: error in parallel transfer
    at org.irods.jargon.core.pub.TransferOperationsHelper.processGetOfSingleFile(TransferOperationsHelper.java:304)
    at org.irods.jargon.core.pub.TransferOperationsHelper.recursivelyGet(TransferOperationsHelper.java:170)
    at org.irods.jargon.core.pub.DataTransferOperationsImpl.getOperationWhenSourceFileIsDirectory(DataTransferOperationsImpl.java:709)
    at org.irods.jargon.core.pub.DataTransferOperationsImpl.processGetAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:491)
    at org.irods.jargon.core.pub.DataTransferOperationsImpl.getOperation(DataTransferOperationsImpl.java:306)
    at org.irods.jargon.core.pub.DataTransferOperationsImpl.getOperation(DataTransferOperationsImpl.java:607)
    at org.irods.jargon.conveyor.core.callables.GetConveyorCallable.processCallForThisTransfer(GetConveyorCallable.java:48)
    at org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable.call(AbstractConveyorCallable.java:208)
    at org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable.call(AbstractConveyorCallable.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.irods.jargon.core.exception.JargonException: error in parallel transfer
    at org.irods.jargon.core.pub.DataObjectAOImpl.processGetAfterResourceDetermined(DataObjectAOImpl.java:1389)
    at org.irods.jargon.core.pub.DataObjectAOImpl.getDataObjectFromIrods(DataObjectAOImpl.java:1043)
    at org.irods.jargon.core.pub.TransferOperationsHelper.processGetOfSingleFile(TransferOperationsHelper.java:296)
    ... 12 more
Caused by: org.irods.jargon.core.exception.FileIntegrityException: checksum verification after get fails
    at org.irods.jargon.core.pub.DataObjectAOImpl.processGetAfterResourceDetermined(DataObjectAOImpl.java:1373)
    ... 14 more
```

Had to just kill iDrop to abort transfer that was hung.

**Comment by michael-conway** [comment]
note...in test 'get' operation from iplant...

```Shell
org.irods.jargon.core.exception.JargonException: error in parallel transfer
	at org.irods.jargon.core.pub.DataObjectAOImpl.processGetAfterResourceDetermined(DataObjectAOImpl.java:1391)
	at org.irods.jargon.core.pub.DataObjectAOImpl.getDataObjectFromIrods(DataObjectAOImpl.java:1044)
	at org.irods.jargon.core.pub.TransferOperationsHelper.processGetOfSingleFile(TransferOperationsHelper.java:306)
	at org.irods.jargon.core.pub.TransferOperationsHelper.recursivelyGet(TransferOperationsHelper.java:180)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.getOperationWhenSourceFileIsDirectory(DataTransferOperationsImpl.java:709)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.processGetAfterAnyConnectionRerouting(DataTransferOperationsImpl.java:491)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.getOperation(DataTransferOperationsImpl.java:306)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.getOperation(DataTransferOperationsImpl.java:607)
	at org.irods.jargon.conveyor.core.callables.GetConveyorCallable.processCallForThisTransfer(GetConveyorCallable.java:48)
	at org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable.call(AbstractConveyorCallable.java:208)
	at org.irods.jargon.conveyor.core.callables.AbstractConveyorCallable.call(AbstractConveyorCallable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.pub.DataObjectAOImpl.checkNbrThreadsAndProcessAsParallelIfMoreThanZeroThreads(DataObjectAOImpl.java:1464)
	at org.irods.jargon.core.pub.DataObjectAOImpl.processGetAfterResourceDetermined(DataObjectAOImpl.java:1332)
	... 14 more
Caused by: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy.transferWithExecutor(ParallelGetFileTransferStrategy.java:175)
	at org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy.transfer(ParallelGetFileTransferStrategy.java:130)
	at org.irods.jargon.core.pub.DataObjectAOImpl.checkNbrThreadsAndProcessAsParallelIfMoreThanZeroThreads(DataObjectAOImpl.java:1457)
	... 15 more
Caused by: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetFileTransferStrategy.transferWithExecutor(ParallelGetFileTransferStrategy.java:164)
	... 17 more
Caused by: org.irods.jargon.core.exception.JargonException: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:137)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:1)
	... 4 more
Caused by: org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:329)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:166)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:123)
	... 5 more
Caused by: org.irods.jargon.core.exception.JargonException: unable to read all the bytes for an expected long value
	at org.irods.jargon.core.transfer.AbstractParallelTransferThread.readLong(AbstractParallelTransferThread.java:70)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:277)
	... 7 more
```

**Comment by michael-conway** [comment]
iput same behavior (same grid, 1 file)

```
From server: NumThreads=16, addr:128.196.172.248, port:20215, cookie=2080588500
ERROR: readMsgHeader:header read- read 0 bytes, expect 4, status = -4060
ERROR: readAndProcApiReply: readMsgHeader error. status = -4060 status = -4060 SYS_HEADER_READ_LEN_ERR, Operation timed out
ERROR: getUtil: get error for ./4.5GBFile.junk status = -4060 SYS_HEADER_READ_LEN_ERR, Operation timed out
Client Caught broken pipe signal. Connection to server may be down
ERROR: writeMsgHeader: wrote 0 bytes for myLen , expect 4, status = -5032
Mike-Conways-MacBook-Pro:temp mikeconway$ 

```

**Comment by michael-conway** [comment]
found this in testing get/put with 1 GB * 100 tries...

```
rsAuthCheck user test1
Sep 18 17:01:33 pid:5802 NOTICE: rsAuthResponse set proxy authFlag to 5, client authFlag to 5, user:test1 proxy:test1 client:test1
Sep 18 17:02:23 pid:5802 NOTICE: _partialDataGet:Bytes written 3485336 don't match read 4194304
Sep 18 17:02:23 pid:5802 ERROR: applyRuleForSvrPortal: acceptSrvPortal error. errno = 107
Sep 18 17:02:23 pid:5802 NOTICE: caught a broken pipe signal and exiting
Sep 18 17:02:23 pid:5802 NOTICE: Agent exiting with status = -7000


```

**Comment by michael-conway** [comment]
another test got 





![image](https://cloud.githubusercontent.com/assets/1097261/6689716/5b0fefd8-cc92-11e4-8dc4-f3a0712a9047.png)

**Comment by michael-conway** [comment]
latest rev looking at get parallel

```

69625 [pool-2-thread-3] DEBUG org.irods.jargon.core.transfer.ParallelGetTransferThread  - socket established, sending cookie to iRODS listener
69626 [pool-2-thread-3] DEBUG org.irods.jargon.core.transfer.ParallelGetTransferThread  - cookie written
69627 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - sockets are open and password sent, now begin the get operation
69627 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - parallel transfer get
69627 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - no connection progress status listener configured, no detailed callbacks
69627 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - opening local randomAccessFile
69627 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - random access file opened rw mode
69631 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - seeking to offset: 527958016
69651 [pool-2-thread-3] DEBUG org.irods.jargon.core.transfer.ParallelGetTransferThread  - reading....
69651 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - >>>>>>>>>>>>> top of while, my length:4194304 <<<<<<<<<<<
69651 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - ===========================
69651 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - ptr:0
69652 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - myLength:4194304
69863 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - >>> read:-1
69939 [pool-2-thread-3] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread  - read < 0
69939 [pool-2-thread-3] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread  - exception in parallel transfer
org.irods.jargon.core.exception.JargonException: did not read expected length
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.myRead(ParallelGetTransferThread.java:396)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:270)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:192)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:149)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
69940 [pool-2-thread-3] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread  - a jargon exception occurred in the get loop
69940 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - parallel thread closing out local random access file stream
69940 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - closing sockets, this close eats exceptions
69940 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - closing local file
69940 [pool-2-thread-3] INFO  org.irods.jargon.core.transfer.ParallelGetTransferThread  - local file closed, exiting get() method
69940 [pool-2-thread-3] ERROR org.irods.jargon.core.transfer.ParallelGetTransferThread  - unchecked exception in transfer
org.irods.jargon.core.exception.JargonException: unexpected exception in parallel transfer
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:342)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.get(ParallelGetTransferThread.java:192)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:149)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.call(ParallelGetTransferThread.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.irods.jargon.core.exception.JargonException: did not read expected length
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.myRead(ParallelGetTransferThread.java:396)
	at org.irods.jargon.core.transfer.ParallelGetTransferThread.processingLoopForGetData(ParallelGetTransferThread.java:270)
	... 7 more

```

**Comment by michael-conway** [comment]
above now fixed in ext commit.
